(function(){
  const panels={obras:'Obras',artistas:'Artistas',leads:'Leads',reservations:'Reservas',proposals:'Propostas',briefs:'Briefings',submissions:'Submissões',certificados:'Certificados',tasks:'Tarefas'};
  const state={panel:'obras',items:[],statusOptions:[],metrics:null,term:'',status:'todos',sort:'recentes'};
  const tokenInput=document.querySelector('[data-admin-token]'); const table=document.querySelector('[data-admin-table]'); const metricsEl=document.querySelector('[data-admin-metrics]'); const statusSelect=document.querySelector('[data-admin-status]'); const searchInput=document.querySelector('[data-admin-search]'); const sortSelect=document.querySelector('[data-admin-sort]');
  const tokenKey='arandu.admin.token'; const sharedTokenKey='arandu.adminToken.v1'; if(tokenInput) tokenInput.value=localStorage.getItem(tokenKey)||localStorage.getItem(sharedTokenKey)||'';
  function esc(v){return String(v??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function token(){const value=tokenInput?.value.trim()||''; if(value){localStorage.setItem(tokenKey,value);localStorage.setItem(sharedTokenKey,value);} return value;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); if(!zone)return; const item=document.createElement('div'); item.className='admin-toast'; item.textContent=text; zone.appendChild(item); setTimeout(()=>item.remove(),3600);}
  async function api(path,opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json','x-arandu-admin-token':token(),...(opts.headers||{})}}); const json=await res.json().catch(()=>({})); if(!res.ok||json.ok===false) throw new Error(json.error||'Erro na operação.'); return json;}
  function label(item){return item.title||item.name||item.client||item.company||item.email||item.code||item.id||'Registro';}
  function sub(item){return item.artist_name||item.artist||item.email||item.whatsapp||item.project_type||item.space||item.entity_type||item.source_page||'';}
  function status(item){return item.status||item.verification_status||item.current_status||'sem status';}
  function date(item){return item.created_at||item.updated_at||item.due_at||'';}
  function itemText(item){return JSON.stringify(item).toLowerCase();}
  function editHref(panel,id){if(panel==='obras')return'obra-editor.html?id='+encodeURIComponent(id); if(panel==='artistas')return'artista-editor.html?id='+encodeURIComponent(id); if(panel==='leads')return'lead-detalhe.html?id='+encodeURIComponent(id); if(panel==='certificados')return'certificados-admin.html?code='+encodeURIComponent(id); return 'editor-registro.html?panel='+encodeURIComponent(panel)+'&id='+encodeURIComponent(id);}
  function publicHref(panel,id){if(panel==='obras')return'obra.html?id='+encodeURIComponent(id); if(panel==='artistas')return'artista.html?id='+encodeURIComponent(id); if(panel==='certificados')return'certificado-imprimivel.html?code='+encodeURIComponent(id); return ''}
  function visible(){let list=[...state.items]; if(state.term)list=list.filter((item)=>itemText(item).includes(state.term)); if(state.status!=='todos')list=list.filter((item)=>status(item)===state.status); if(state.sort==='nome')list.sort((a,b)=>label(a).localeCompare(label(b),'pt-BR')); if(state.sort==='status')list.sort((a,b)=>status(a).localeCompare(status(b),'pt-BR')); if(state.sort==='recentes')list.sort((a,b)=>String(date(b)).localeCompare(String(date(a)))); return list;}
  function renderMetrics(){const m=state.metrics||{}; const rows=[['Obras',m.artworks],['Artistas',m.artists],['Leads',m.leads],['Reservas',m.reservations],['Propostas',m.proposals],['Certificados',m.certificates],['Submissões',m.submissions],['Tarefas',m.tasks]]; metricsEl.innerHTML=rows.map(([k,v])=>'<article class="admin-metric"><strong>'+esc(v??0)+'</strong><span>'+esc(k)+'</span></article>').join('');}
  function renderStatus(){statusSelect.innerHTML='<option value="todos">Todos os status</option>'+state.statusOptions.map((s)=>'<option value="'+esc(s)+'">'+esc(s)+'</option>').join(''); statusSelect.value=state.status;}
  function renderTable(){document.querySelector('[data-admin-panel-label]').textContent=panels[state.panel]||state.panel; const list=visible(); if(!list.length){table.innerHTML='<div class="op-empty"><strong>Nenhum registro encontrado</strong><span>Altere filtros ou carregue outro painel.</span></div>';return;} table.innerHTML=list.map((item)=>{const id=String(item.id||item.code||''); const st=esc(status(item)); const pub=publicHref(state.panel,id); return '<article class="admin-row"><div><strong>'+esc(label(item))+'</strong><br><small>'+esc(sub(item))+'</small></div><small>'+esc(id)+'</small><small>'+st+'</small><div class="admin-actions"><a class="secondary" href="'+esc(editHref(state.panel,id))+'">Editar</a>'+(pub?'<a class="secondary" href="'+esc(pub)+'">Público</a>':'')+'<button type="button" data-cycle-status="'+esc(id)+'">Status</button><button class="secondary" type="button" data-copy-id="'+esc(id)+'">Copiar ID</button></div></article>';}).join('');}
  function render(){renderMetrics();renderStatus();renderTable(); document.querySelectorAll('[data-admin-tabs] [data-panel]').forEach((b)=>b.classList.toggle('is-active',b.dataset.panel===state.panel));}
  async function loadMetrics(){try{const data=await api('/api/dashboard'); state.metrics=data.metrics||{};}catch{state.metrics={};}}
  async function loadPanel(panel=state.panel){state.panel=panel; table.innerHTML='<div class="op-empty"><strong>Carregando</strong><span>Consultando '+esc(panels[panel]||panel)+'...</span></div>'; await loadMetrics(); const data=await api('/api/admin?panel='+encodeURIComponent(panel)); state.items=data.items||[]; state.statusOptions=data.statusOptions||[]; state.status='todos'; render(); toast('Painel carregado: '+(panels[panel]||panel));}
  async function cycleStatus(id){const index=state.items.findIndex((item)=>String(item.id||item.code)===String(id)); if(index<0||!state.statusOptions.length)return; const item=state.items[index]; const current=status(item); const next=state.statusOptions[(state.statusOptions.indexOf(current)+1)%state.statusOptions.length]||state.statusOptions[0]; await api('/api/admin',{method:'PATCH',body:JSON.stringify({panel:state.panel,id,status:next})}); toast('Status atualizado para '+next); await loadPanel(state.panel);}
  document.querySelector('[data-admin-load]')?.addEventListener('click',()=>loadPanel().catch(e=>toast(e.message)));
  document.querySelector('[data-admin-tabs]')?.addEventListener('click',(e)=>{const b=e.target.closest('[data-panel]'); if(b)loadPanel(b.dataset.panel).catch(err=>toast(err.message));});
  searchInput?.addEventListener('input',()=>{state.term=searchInput.value.toLowerCase();renderTable();});
  statusSelect?.addEventListener('change',()=>{state.status=statusSelect.value;renderTable();}); sortSelect?.addEventListener('change',()=>{state.sort=sortSelect.value;renderTable();});
  table?.addEventListener('click',async(e)=>{const cycle=e.target.closest('[data-cycle-status]'); const copy=e.target.closest('[data-copy-id]'); if(cycle){await cycleStatus(cycle.dataset.cycleStatus).catch(err=>toast(err.message));} if(copy){await navigator.clipboard.writeText(copy.dataset.copyId);toast('ID copiado.');}});
  if(token()) loadPanel().catch(()=>{});
})();
