/* Arandu — assistente de jornada pública */
(function(){
  const SKIP=/^(painel|admin|demo|roadmap|configuracao|login|cadastro|minha-conta)/i;
  function page(){return location.pathname.split('/').pop()||'index.html'}
  function isInternal(){return SKIP.test(page())}
  function readArray(key){try{const data=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(data)?data:[]}catch{return[]}}
  function readObject(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return{}}}
  function hasBriefing(){const b=readObject('arandu.selection.briefing.v1');return Boolean(b.ambiente||b.orcamento||b.sensacao||b.prazo||b.observacoes)}
  function state(){return{recent:readArray('arandu.recentlyViewed.v1').length,selection:readArray('arandu.selection.v1').length,compare:readArray('arandu.compare.v1').length,briefing:hasBriefing(),proposal:readArray('arandu.proposals.history.v1').length}}
  function pct(s){let score=0;if(s.recent)score+=20;if(s.selection)score+=25;if(s.compare)score+=20;if(s.briefing)score+=20;if(s.proposal)score+=15;return Math.min(score,100)}
  function step(label,done,href){const li=document.createElement('li');li.className=done?'is-done':'';const a=document.createElement('a');a.href=href;a.textContent=label;li.appendChild(a);return li}
  function buildPanel(){const s=state();let panel=document.querySelector('[data-arandu-journey-panel]');if(panel)return panel;panel=document.createElement('aside');panel.className='arandu-journey-panel';panel.dataset.aranduJourneyPanel='true';panel.hidden=true;const header=document.createElement('div');header.className='arandu-journey-head';const copy=document.createElement('div');const eyebrow=document.createElement('p');eyebrow.className='eyebrow';eyebrow.textContent='Jornada de compra';const title=document.createElement('strong');title.textContent='Seu caminho na Arandu';copy.append(eyebrow,title);const close=document.createElement('button');close.type='button';close.dataset.closeJourney='true';close.textContent='×';header.append(copy,close);const progress=document.createElement('div');progress.className='arandu-journey-progress';const bar=document.createElement('span');bar.style.width=pct(s)+'%';progress.appendChild(bar);const summary=document.createElement('p');summary.className='arandu-journey-summary';summary.textContent=pct(s)+'% da jornada preparada';const list=document.createElement('ol');list.append(step('Ver obras',Boolean(s.recent),'obras.html'));list.append(step('Salvar seleção',Boolean(s.selection),'minha-selecao.html'));list.append(step('Comparar alternativas',Boolean(s.compare),'comparar-obras.html'));list.append(step('Completar briefing',Boolean(s.briefing),'minha-selecao.html#briefing'));list.append(step('Gerar proposta',Boolean(s.proposal),'proposta-curatorial.html'));const actions=document.createElement('div');actions.className='page-actions';const primary=document.createElement('a');primary.className='cta secondary';primary.href=s.selection?'minha-selecao.html':'obras.html';primary.textContent=s.selection?'Abrir seleção':'Começar pelo acervo';const secondary=document.createElement('a');secondary.className='cta secondary';secondary.href='contato.html';secondary.textContent='Falar com curadoria';actions.append(primary,secondary);panel.append(header,progress,summary,list,actions);document.body.appendChild(panel);return panel}
  function buildButton(){let button=document.querySelector('[data-arandu-journey-button]');if(button)return button;button=document.createElement('button');button.type='button';button.className='arandu-journey-button';button.dataset.aranduJourneyButton='true';button.textContent='Jornada';document.body.appendChild(button);return button}
  function refresh(){if(isInternal())return;const panel=document.querySelector('[data-arandu-journey-panel]');if(panel)panel.remove();buildPanel();}
  document.addEventListener('click',function(event){if(event.target.closest('[data-arandu-journey-button]')){event.preventDefault();const panel=buildPanel();panel.hidden=!panel.hidden}if(event.target.closest('[data-close-journey]')){event.preventDefault();const panel=document.querySelector('[data-arandu-journey-panel]');if(panel)panel.hidden=true}});
  document.addEventListener('arandu:selection-updated',refresh);
  document.addEventListener('DOMContentLoaded',function(){if(isInternal())return;setTimeout(function(){buildButton();buildPanel()},1200)});
})();
