/* Arandu — obras vistas recentemente */
(function(){
  const KEY='arandu.recentlyViewed.v1';
  const SKIP=/^(painel|admin|demo|roadmap|configuracao|login|cadastro|minha-conta)/i;
  function page(){return location.pathname.split('/').pop()||'index.html'}
  function isInternal(){return SKIP.test(page())}
  function read(){try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(data)?data:[]}catch{return[]}}
  function write(items){localStorage.setItem(KEY,JSON.stringify(items.slice(0,8)))}
  function text(selector){return document.querySelector(selector)?.textContent?.trim()||''}
  function currentArtworkId(){return new URLSearchParams(location.search).get('id')||''}
  function saveCurrentArtwork(){if(page()!=='obra.html')return;const id=currentArtworkId();if(!id)return;setTimeout(function(){const title=text('h1.title')||document.title.replace('— Arandu','').trim()||id;const artist=text('.artwork-facts p:first-child')||'';const current={id,title,artist:artist.replace('Artista','').trim(),url:'obra.html?id='+id,seenAt:new Date().toISOString()};const items=read().filter(function(item){return item.id!==id});items.unshift(current);write(items)},900)}
  function createCard(item){const article=document.createElement('article');article.className='card';const eyebrow=document.createElement('p');eyebrow.className='eyebrow';eyebrow.textContent='Vista recentemente';const title=document.createElement('h3');title.textContent=item.title||'Obra Arandu';const artist=document.createElement('p');artist.textContent=item.artist||'Retomar leitura curatorial';const actions=document.createElement('div');actions.className='page-actions';const link=document.createElement('a');link.className='cta secondary';link.href=item.url||'obras.html';link.textContent='Reabrir';actions.appendChild(link);article.append(eyebrow,title,artist,actions);return article}
  function renderRecent(){if(isInternal())return;const allowed=['index.html','obras.html','comprar-arte.html','acervo.html','minha-selecao.html','comparar-obras.html','proposta-curatorial.html'];if(!allowed.includes(page()))return;const items=read();if(!items.length||document.querySelector('[data-recently-viewed]'))return;const main=document.querySelector('main');if(!main)return;const section=document.createElement('section');section.className='clean-section section-muted';section.dataset.recentlyViewed='true';const container=document.createElement('div');container.className='container';const head=document.createElement('div');head.className='section-head';const copy=document.createElement('div');const eyebrow=document.createElement('p');eyebrow.className='eyebrow';eyebrow.textContent='Continue de onde parou';const h2=document.createElement('h2');h2.className='section-title';h2.textContent='Obras vistas recentemente.';copy.append(eyebrow,h2);const clear=document.createElement('button');clear.className='cta secondary';clear.type='button';clear.dataset.clearRecent='true';clear.textContent='Limpar histórico';head.append(copy,clear);const grid=document.createElement('div');grid.className='clean-grid';items.slice(0,3).forEach(function(item){grid.appendChild(createCard(item))});container.append(head,grid);section.appendChild(container);main.appendChild(section)}
  document.addEventListener('click',function(event){if(event.target.closest('[data-clear-recent]')){event.preventDefault();write([]);document.querySelector('[data-recently-viewed]')?.remove()}});
  document.addEventListener('DOMContentLoaded',function(){if(isInternal())return;saveCurrentArtwork();setTimeout(renderRecent,1100)});
})();
