(function(){
  const form=document.querySelector('[data-artist-editor]'); if(!form)return;
  const tokenInput=document.querySelector('[data-admin-token]'); const tokenKey='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(tokenKey)||'';
  const statusEl=document.querySelector('[data-artist-editor-status]'); const preview=document.querySelector('[data-artist-preview]'); const titleEl=document.querySelector('[data-artist-preview-title]'); const metaEl=document.querySelector('[data-artist-preview-meta]'); const qualityEl=document.querySelector('[data-artist-quality]'); const params=new URLSearchParams(location.search); if(params.get('id'))form.id.value=params.get('id');
  function token(){const t=tokenInput?.value.trim()||''; if(t)localStorage.setItem(tokenKey,t); return t;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); const item=document.createElement('div'); item.className='admin-toast'; item.textContent=text; zone.appendChild(item); setTimeout(()=>item.remove(),3500);}
  async function api(path,opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json','x-arandu-admin-token':token(),...(opts.headers||{})}}); const json=await res.json().catch(()=>({})); if(!res.ok||json.ok===false)throw new Error(json.error||'Erro administrativo.'); return json;}
  function list(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean);}
  function getFields(){const fd=new FormData(form); const id=fd.get('id'); const fields={}; ['name','legal_name','city','state','region','artist_level','image_url','studio_image_url','instagram','portfolio_url','status','profile','trajectory','statement'].forEach(k=>{const v=fd.get(k); if(v!==''&&v!==null)fields[k]=v;}); ['languages','curatorial_axes'].forEach(k=>{const v=list(fd.get(k)); if(v.length)fields[k]=v;}); return {id,fields};}
  function fill(item){if(!item)return; ['id','name','legal_name','city','state','region','artist_level','image_url','studio_image_url','instagram','portfolio_url','status','profile','trajectory','statement'].forEach(k=>{if(form.elements[k]&&item[k]!==undefined&&item[k]!==null)form.elements[k].value=item[k];}); ['languages','curatorial_axes'].forEach(k=>{if(form.elements[k]&&Array.isArray(item[k]))form.elements[k].value=item[k].join(', ');}); renderPreview();}
  function renderPreview(){const {fields}=getFields(); titleEl.textContent=fields.name||'Artista sem nome'; metaEl.textContent=[fields.city,fields.state,(fields.languages||[]).join(', '),fields.status].filter(Boolean).join(' · ')||'Perfil em edição.'; preview.innerHTML=fields.image_url?'<img src="'+fields.image_url+'" alt="prévia">':'Sem foto'; const issues=[]; if(!fields.image_url)issues.push('sem foto'); if(!fields.city)issues.push('sem cidade'); if(!fields.profile)issues.push('sem bio'); if(!fields.languages?.length)issues.push('sem linguagem'); qualityEl.innerHTML='<p class="eyebrow">Qualidade</p>'+(issues.length?issues.map(i=>'<span class="af-badge warn">'+i+'</span>').join(' '):'<span class="af-badge ok">perfil completo</span>');}
  async function load(){const id=form.id.value.trim(); if(!id)throw new Error('Informe o ID do artista.'); statusEl.textContent='Carregando...'; const data=await api('/api/admin?panel=artistas'); const item=(data.items||[]).find(r=>String(r.id)===id); if(!item)throw new Error('Artista não encontrado.'); fill(item); statusEl.textContent='Artista carregado.'; toast('Artista carregado.');}
  async function save(extra={}){const {id,fields}=getFields(); if(!id)throw new Error('Informe o ID.'); await api('/api/admin-update',{method:'PATCH',body:JSON.stringify({panel:'artistas',id,fields:{...fields,...extra}})}); statusEl.textContent='Artista salvo.'; toast('Artista salvo.');}
  form.addEventListener('input',renderPreview); form.addEventListener('submit',async(e)=>{e.preventDefault(); try{await save();}catch(err){statusEl.textContent=err.message;toast(err.message);}});
  document.querySelector('[data-load-artist]')?.addEventListener('click',()=>load().catch(e=>{statusEl.textContent=e.message;toast(e.message);}));
  document.querySelector('[data-publish-artist]')?.addEventListener('click',()=>{form.status.value='published';save({status:'published'}).catch(e=>toast(e.message));});
  document.querySelector('[data-open-artist]')?.addEventListener('click',()=>{if(form.id.value)location.href='artista.html?id='+encodeURIComponent(form.id.value.trim());});
  renderPreview(); if(form.id.value&&tokenInput.value)load().catch(()=>{});
})();
