(function(){
  const form=document.querySelector('[data-artwork-editor]'); if(!form)return;
  const tokenInput=document.querySelector('[data-admin-token]'); const tokenKey='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(tokenKey)||'';
  const statusEl=document.querySelector('[data-artwork-editor-status]'); const preview=document.querySelector('[data-artwork-preview]'); const titleEl=document.querySelector('[data-artwork-preview-title]'); const metaEl=document.querySelector('[data-artwork-preview-meta]'); const qualityEl=document.querySelector('[data-artwork-quality]');
  const params=new URLSearchParams(location.search); if(params.get('id')) form.id.value=params.get('id');
  function token(){const t=tokenInput?.value.trim()||''; if(t)localStorage.setItem(tokenKey,t); return t;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); const item=document.createElement('div'); item.className='admin-toast'; item.textContent=text; zone.appendChild(item); setTimeout(()=>item.remove(),3500);}
  async function api(path,opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json','x-arandu-admin-token':token(),...(opts.headers||{})}}); const json=await res.json().catch(()=>({})); if(!res.ok||json.ok===false)throw new Error(json.error||'Erro administrativo.'); return json;}
  function list(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean);}
  function getFields(){const fd=new FormData(form); const id=fd.get('id'); const fields={}; ['title','artist_id','technique','type','support','year','dimensions','price','price_label','status','edition','edition_size','main_image_url','detail_image_url','room_image_url','summary','curatorial_reading'].forEach((k)=>{const v=fd.get(k); if(v!==''&&v!==null)fields[k]=v;}); ['tags','spaces','recommended_for'].forEach((k)=>{const v=list(fd.get(k)); if(v.length)fields[k]=v;}); return {id,fields};}
  function fill(item){if(!item)return; ['id','title','artist_id','technique','type','support','year','dimensions','price','price_label','status','edition','edition_size','main_image_url','detail_image_url','room_image_url','summary','curatorial_reading'].forEach((k)=>{if(form.elements[k]&&item[k]!==undefined&&item[k]!==null)form.elements[k].value=item[k];}); ['tags','spaces','recommended_for'].forEach((k)=>{if(form.elements[k]&&Array.isArray(item[k]))form.elements[k].value=item[k].join(', ');}); renderPreview();}
  function quality(){const {fields}=getFields(); const issues=[]; if(!fields.main_image_url)issues.push('sem imagem'); if(!fields.price&&!fields.price_label)issues.push('sem preço'); if(!fields.summary)issues.push('sem resumo'); if(!fields.curatorial_reading)issues.push('sem leitura'); if(!fields.tags?.length)issues.push('sem tags'); return issues;}
  function renderPreview(){const {fields}=getFields(); titleEl.textContent=fields.title||'Obra sem título'; metaEl.textContent=[fields.technique,fields.dimensions,fields.price_label||fields.price,fields.status].filter(Boolean).join(' · ')||'Ficha em edição.'; preview.innerHTML=fields.main_image_url?'<img src="'+fields.main_image_url+'" alt="prévia">':'Sem imagem'; const issues=quality(); qualityEl.innerHTML='<p class="eyebrow">Qualidade</p>'+(issues.length?issues.map(i=>'<span class="af-badge warn">'+i+'</span>').join(' '):'<span class="af-badge ok">cadastro completo</span>');}
  async function load(){const id=form.id.value.trim(); if(!id)throw new Error('Informe o ID da obra.'); statusEl.textContent='Carregando...'; const data=await api('/api/admin?panel=obras'); const item=(data.items||[]).find(r=>String(r.id)===id); if(!item)throw new Error('Obra não encontrada.'); fill(item); statusEl.textContent='Obra carregada.'; toast('Obra carregada.');}
  async function save(extra={}){const {id,fields}=getFields(); if(!id)throw new Error('Informe o ID.'); const payload={...fields,...extra}; await api('/api/admin-update',{method:'PATCH',body:JSON.stringify({panel:'obras',id,fields:payload})}); statusEl.textContent='Obra salva.'; toast('Obra salva.');}
  async function markSold(){await save({status:'sold'}); form.status.value='sold'; renderPreview();}
  function generateCertificate(){const id=form.id.value.trim(); if(!id)return; location.href='certificados-admin.html?artwork_id='+encodeURIComponent(id);}
  form.addEventListener('input',renderPreview); form.addEventListener('submit',async(e)=>{e.preventDefault(); try{await save();}catch(err){statusEl.textContent=err.message;toast(err.message);}});
  document.querySelector('[data-load-artwork]')?.addEventListener('click',()=>load().catch(e=>{statusEl.textContent=e.message;toast(e.message);}));
  document.querySelector('[data-mark-sold]')?.addEventListener('click',()=>markSold().catch(e=>toast(e.message)));
  document.querySelector('[data-generate-certificate]')?.addEventListener('click',generateCertificate);
  document.querySelector('[data-open-artwork]')?.addEventListener('click',()=>{if(form.id.value)location.href='obra.html?id='+encodeURIComponent(form.id.value.trim());});
  renderPreview(); if(form.id.value&&tokenInput.value)load().catch(()=>{});
})();
