function escapeArtistHtml(value) {
  return String(value || '').replace(/[&<>'"]/g, function (char) {
    return { '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char];
  });
}
function setArtistMeta(name, content, attr) { if (!content) return; var selector = attr === 'property' ? 'meta[property="' + name + '"]' : 'meta[name="' + name + '"]'; var meta = document.querySelector(selector); if (!meta) { meta = document.createElement('meta'); meta.setAttribute(attr || 'name', name); document.head.appendChild(meta); } meta.setAttribute('content', content); }
function setArtistCanonical(url) { var link = document.querySelector('link[rel="canonical"]'); if (!link) { link = document.createElement('link'); link.rel = 'canonical'; document.head.appendChild(link); } link.href = url; }
function setArtistJsonLd(id, data) { var old = document.getElementById(id); if (old) old.remove(); var script = document.createElement('script'); script.type = 'application/ld+json'; script.id = id; script.textContent = JSON.stringify(data); document.head.appendChild(script); }
function setArtistSeo(artist, works) { var url = location.origin + location.pathname + '?id=' + encodeURIComponent(artist.id); var desc = (artist.profile || (artist.name + ', artista acompanhado pela Arandu.')).slice(0, 160); document.title = artist.name + ' — Artista | Arandu'; setArtistMeta('description', desc); setArtistMeta('og:title', document.title, 'property'); setArtistMeta('og:description', desc, 'property'); setArtistMeta('og:type', 'profile', 'property'); setArtistMeta('og:url', url, 'property'); if (artist.image) setArtistMeta('og:image', artist.image, 'property'); setArtistCanonical(url); setArtistJsonLd('artist-jsonld', { '@context': 'https://schema.org', '@type': 'Person', name: artist.name, description: desc, image: artist.image || undefined, homeLocation: artist.city || undefined, url, knowsAbout: (artist.languages || []).concat(artist.curatorialAxes || []), mainEntityOfPage: url, workExample: works.slice(0, 5).map(function (work) { return { '@type': 'VisualArtwork', name: work.title, url: location.origin + '/obra.html?id=' + encodeURIComponent(work.id) }; }) }); }
function tagList(items) { return (items || []).slice(0, 8).map(function (item) { return '<span class="tag">' + escapeArtistHtml(item) + '</span>'; }).join(''); }
function artistFact(label, value) { return '<p><strong>' + escapeArtistHtml(label) + '</strong>' + escapeArtistHtml(value || 'a confirmar') + '</p>'; }
function imageUrl(item) { return item.image_url || item.photo_url || item.studio_image_url || item.avatar_url || item.main_image_url || item.image || ''; }
function normalizeArtist(item) { return { ...item, id: item.id, name: item.name || item.artist || 'Artista Arandu', city: item.city || item.location || item.origin || 'Brasil', state: item.state || '', region: item.region || '', languages: item.languages || item.language_tags || [], curatorialAxes: item.curatorialAxes || item.curatorial_axes || [], profile: item.profile || item.bio || item.summary || 'Trajetória em acompanhamento curatorial.', trajectory: item.trajectory || item.career_note || '', statement: item.statement || item.artist_statement || '', artistLevel: item.artistLevel || item.artist_level || 'developing', image: imageUrl(item) }; }
function normalizeWork(work) { return { ...work, id: work.id, title: work.title || 'Obra sem título', artistId: work.artistId || work.artist_id, artist: work.artist || work.artist_name || work.artists?.name || '', type: work.type || work.language || work.technique || 'Obra', status: work.status || 'disponível', technique: work.technique || '', priceLabel: work.priceLabel || work.price_label || 'sob consulta', thumb: work.thumb || work.image_class || 'thumb-terra', image: imageUrl(work) }; }
function workCard(work) { var media = work.image ? '<div class="op-card-media"><img src="' + escapeArtistHtml(work.image) + '" alt="' + escapeArtistHtml(work.title) + '"></div>' : '<div class="op-card-media ' + escapeArtistHtml(work.thumb || 'thumb-terra') + '"></div>'; return '<a class="ux-work-card" href="obra.html?id=' + escapeArtistHtml(work.id) + '">' + media + '<strong>' + escapeArtistHtml(work.title) + '</strong><span class="artist">' + escapeArtistHtml(work.type || 'Obra') + ' · ' + escapeArtistHtml(work.status || 'disponível') + '</span><div class="op-work-foot"><span class="op-price">' + escapeArtistHtml(work.priceLabel || 'sob consulta') + '</span><span class="op-mini-link">Ver obra →</span></div></a>'; }
async function loadArtists() { if (!window.AranduCatalogSource) throw new Error('Fonte de artistas não carregada.'); return (await window.AranduCatalogSource.artists()).map(normalizeArtist); }
async function loadWorks() { if (!window.AranduCatalogSource) throw new Error('Fonte do catálogo não carregada.'); return (await window.AranduCatalogSource.catalog()).map(normalizeWork); }
function artistPhoto(artist) { if (artist.image) return '<div class="op-card-media artist-portrait-large"><img src="' + escapeArtistHtml(artist.image) + '" alt="' + escapeArtistHtml(artist.name) + '"></div>'; return '<div class="op-card-media artist-portrait-large artist-face large"></div>'; }
async function autor() {
  var box = document.querySelector('[data-artist-page]'); if (!box) return;
  var id = new URLSearchParams(location.search).get('id');
  try {
    var results = await Promise.all([loadArtists(), loadWorks()]); var artists = results[0]; var works = results[1]; var artist = artists.find(function (item) { return item.id === id; }); if (!artist) throw new Error('Artista não encontrado no catálogo verificado.');
    var artistWorks = works.filter(function (work) { return work.artistId === artist.id || work.artist === artist.name; }); var availableWorks = artistWorks.filter(function (work) { return !/vendida|sold|indisponível|indisponivel/i.test(String(work.status || '')); }); var soldWorks = artistWorks.filter(function (work) { return /vendida|sold/i.test(String(work.status || '')); }); var levelLabel = artist.artistLevel === 'emerging' ? 'artista emergente' : 'artista em desenvolvimento';
    setArtistSeo(artist, artistWorks);
    box.innerHTML = '<article class="artist-premium-page"><section class="artist-hero-detail"><div>' + artistPhoto(artist) + '</div><div><p class="eyebrow">Artista Arandu · ' + escapeArtistHtml(levelLabel) + '</p><h1 class="title">' + escapeArtistHtml(artist.name) + '</h1><p class="lead">' + escapeArtistHtml(artist.profile) + '</p><div class="artist-facts enhanced-facts">' + artistFact('Cidade', [artist.city, artist.state].filter(Boolean).join(' · ')) + artistFact('Região', artist.region) + artistFact('Linguagens', (artist.languages || []).join(', ')) + artistFact('Eixos curatoriais', (artist.curatorialAxes || []).join(', ')) + '</div><div class="tags">' + tagList(artist.languages) + tagList(artist.curatorialAxes) + '</div></div></section><section class="premium-reading artist-statement-block"><div><p class="eyebrow">Declaração</p><h2>O que move a pesquisa.</h2><p>' + escapeArtistHtml(artist.statement || artist.profile) + '</p></div><div><p class="eyebrow">Trajetória</p><p>' + escapeArtistHtml(artist.trajectory || 'Trajetória em organização para acompanhamento curatorial.') + '</p></div></section><section class="trust-strip artist-trust-strip"><article class="trust-card"><strong>' + escapeArtistHtml(availableWorks.length) + '</strong><span>obras disponíveis ou em conversa.</span></article><article class="trust-card"><strong>' + escapeArtistHtml(soldWorks.length) + '</strong><span>obras vendidas ou registradas.</span></article><article class="trust-card"><strong>Perfil</strong><span>Bio, linguagem, território e leitura de processo.</span></article><article class="trust-card"><strong>Procedência</strong><span>Ficha técnica, autoria e certificado por obra.</span></article></section><section class="artist-works-section"><div class="section-head"><div><p class="eyebrow">Obras no acervo</p><h2 class="section-title">Disponíveis, reservadas e vendidas.</h2></div><a class="cta secondary" href="artistas.html">Ver todos os artistas</a></div><div class="ux-work-grid">' + (artistWorks.length ? artistWorks.map(workCard).join('') : '<div class="op-empty"><strong>Nenhuma obra carregada</strong><span>Este artista ainda não possui obras vinculadas ao catálogo público.</span></div>') + '</div></section><section class="collector-guidance"><div><p class="eyebrow">Leitura de carreira</p><h2 class="section-title">Como acompanhar este artista.</h2></div><ol class="process-steps"><li>Observe recorrências de linguagem, técnica e território.</li><li>Compare obras disponíveis com obras vendidas ou reservadas.</li><li>Considere escala, série, documentação e momento da trajetória.</li><li>Fale com a curadoria para entender evolução de preço e novas séries.</li></ol></section></article>';
  } catch (error) { var message = window.AranduCatalogSource?.message(error, 'cadastro de artistas') || error.message; box.innerHTML = '<div class="op-empty catalog-unavailable"><h1 class="title">Artista indisponível</h1><p>' + escapeArtistHtml(message) + '</p><a class="cta secondary" href="artistas.html">Ver artistas</a></div>'; }
}
document.addEventListener('DOMContentLoaded', autor);
