const CATALOG_SYNONYMS = {
  quadro: 'pintura tela obra parede', decoracao: 'casa ambiente sala apartamento interiores', barato: 'ate-3000 primeira-obra acessivel fotografia', acessivel: 'ate-3000 primeira-obra fotografia', escritorio: 'empresa corporativo recepcao sala reuniao', clinica: 'consultorio saude acolhimento silencio recepcao paciente', consultorio: 'clinica saude acolhimento silencio', hotel: 'hospitalidade hotelaria recepcao permanencia', restaurante: 'hospitalidade atmosfera permanencia', calma: 'acolhimento silencio memoria serenidade', impacto: 'presenca empresa recepcao escultura', certificado: 'autenticidade procedencia ficha tecnica', sala: 'casa apartamento parede estar receber decoração', natureza: 'terra paisagem rio materia brasilidade', urbano: 'cidade gesto movimento metropole grafismo', coloridas: 'cor vibrante impacto brasilidade', minimalista: 'silencio calma leveza clinica quarto', primeira: 'primeira-obra acessivel compra inicial'
};
function normalize(value){return(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function escapeCatalogHtml(value){return String(value||'').replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function expandCatalogQuery(query){const q=normalize(query);const synonyms=q.split(/\s+/).map((term)=>CATALOG_SYNONYMS[term]||'').join(' ');return normalize(`${q} ${synonyms}`).split(/\s+/).filter(Boolean)}
function mapApiArtwork(item){return{...item,id:item.id,title:item.title,artist:item.artist||item.artist_name||item.artists?.name||'Artista Arandu',artistId:item.artistId||item.artist_id,type:item.type||item.language||'Obra',technique:item.technique,dimensions:item.dimensions,price:item.price,priceLabel:item.priceLabel||item.price_label,status:item.status,edition:item.edition,certificate:item.certificate,thumb:item.thumb,recommendedFor:item.recommendedFor||item.recommended_for||[],tags:item.tags||[],moods:item.moods||[],spaces:item.spaces||[],search:item.search,summary:item.summary,curatorialReading:item.curatorialReading||item.curatorial_reading,firstArtwork:item.firstArtwork||item.first_artwork}}
async function loadFromApi(){try{const response=await fetch('/api/catalog',{cache:'no-store'});const data=await response.json().catch(()=>({}));if(response.ok&&Array.isArray(data.items)&&data.items.length)return data.items.map(mapApiArtwork)}catch{}return[]}
async function loadFromStatic(){try{const response=await fetch('data/artworks.json',{cache:'no-store'});if(!response.ok)throw new Error('artworks');const data=await response.json();return Array.isArray(data)?data:[]}catch{return[]}}
async function loadArtworkData(){const api=await loadFromApi();return api.length?api:await loadFromStatic()}
function artworkTags(artwork){return[artwork.type,artwork.technique,artwork.status,...(artwork.tags||[]),...(artwork.moods||[]),...(artwork.spaces||[]),...(artwork.recommendedFor||[])].join(' ')}
function statusLabel(status){const value=String(status||'disponível').toLowerCase();if(value.includes('sold')||value.includes('vend'))return'Vendida';if(value.includes('reserved')||value.includes('reserv'))return'Reservada';return'Disponível'}
function reserveDisabled(artwork){const value=String(artwork.status||'').toLowerCase();return value.includes('vendida')||value.includes('sold')}
function renderArtworkCard(artwork,index){const tags=normalize(artworkTags(artwork));const search=`${artwork.title} ${artwork.artist} ${artwork.technique} ${artwork.summary} ${artwork.search||''}`;const context=(artwork.tags||[]).slice(0,3).join(' · ');const status=statusLabel(artwork.status);const uses=(artwork.recommendedFor||artwork.spaces||[]).slice(0,3).map((item)=>`<span>${escapeCatalogHtml(item)}</span>`).join('');const cardTags=(artwork.tags||[]).slice(0,3).map((tag)=>`<span>${escapeCatalogHtml(String(tag).replace(/-/g,' '))}</span>`).join('');return`
  <article class="card catalog-card commerce-product-card" data-catalog-card data-order="${index+1}" data-price="${Number(artwork.price||0)}" data-tags="${escapeCatalogHtml(tags)}" data-search="${escapeCatalogHtml(search)}">
    <a class="commerce-product-image" href="obra.html?id=${escapeCatalogHtml(artwork.id)}" aria-label="Ver ${escapeCatalogHtml(artwork.title)}">
      <span class="commerce-product-badges"><span>${escapeCatalogHtml(status)}</span>${artwork.certificate?'<span>Certificada</span>':''}</span>
      <div class="thumb ${escapeCatalogHtml(artwork.thumb||'thumb-terra')}"></div>
    </a>
    <div class="commerce-product-copy">
      <div class="commerce-product-meta"><span>${escapeCatalogHtml(artwork.type||'Obra')}</span><span>${escapeCatalogHtml(artwork.edition||'Obra registrada')}</span></div>
      <p class="commerce-product-artist">${escapeCatalogHtml(artwork.artist)}</p>
      <h3>${escapeCatalogHtml(artwork.title)}</h3>
      <p>${escapeCatalogHtml(artwork.technique||'Técnica a confirmar')} · ${escapeCatalogHtml(artwork.dimensions||'Dimensão a confirmar')}</p>
      <p class="commerce-product-price">${escapeCatalogHtml(artwork.priceLabel||'Sob consulta')}</p>
      <p>${escapeCatalogHtml(artwork.summary||'Obra selecionada pela curadoria Arandu.')}</p>
      <div class="commerce-product-meta">${uses}</div>
      <div class="commerce-product-tags">${cardTags}</div>
      <div class="commerce-product-actions"><a class="cta" href="obra.html?id=${escapeCatalogHtml(artwork.id)}">Ver obra</a><button class="cta secondary" type="button" ${reserveDisabled(artwork)?'disabled':''} data-reserve-artwork="${escapeCatalogHtml(artwork.id)}" data-reserve-title="${escapeCatalogHtml(artwork.title)}" data-reserve-artist="${escapeCatalogHtml(artwork.artist)}" data-reserve-url="obra.html?id=${escapeCatalogHtml(artwork.id)}">Reservar</button></div>
      <button class="cta secondary" type="button" data-save-artwork="${escapeCatalogHtml(artwork.id)}" data-artwork-title="${escapeCatalogHtml(artwork.title)}" data-artwork-artist="${escapeCatalogHtml(artwork.artist)}" data-artwork-context="${escapeCatalogHtml(context)}" data-artwork-url="obra.html?id=${escapeCatalogHtml(artwork.id)}" data-artwork-price="${escapeCatalogHtml(String(artwork.price||''))}" data-artwork-price-label="${escapeCatalogHtml(artwork.priceLabel||'')}" data-artwork-technique="${escapeCatalogHtml(artwork.technique||'')}" data-artwork-dimensions="${escapeCatalogHtml(artwork.dimensions||'')}" data-artwork-status="${escapeCatalogHtml(artwork.status||'')}" data-artwork-thumb="${escapeCatalogHtml(artwork.thumb||'')}">Salvar na seleção</button>
    </div>
  </article>`}
function renderCatalogFromData(artworks){const grid=document.querySelector('[data-catalog-grid]');if(!grid||!artworks.length)return;grid.innerHTML=artworks.map(renderArtworkCard).join('')}
function getActiveFilter(){return document.querySelector('[data-filter].is-active')?.dataset.filter||'todos'}
function parsePrice(card){return Number(String(card.dataset.price||'0').replace(/[^0-9]/g,''))||0}
function sortCatalog(){const select=document.querySelector('[data-catalog-sort]');const grid=document.querySelector('[data-catalog-grid]');if(!select||!grid)return;const cards=Array.from(grid.querySelectorAll('[data-catalog-card]'));const mode=select.value;cards.sort((a,b)=>{if(mode==='preco-menor')return parsePrice(a)-parsePrice(b);if(mode==='preco-maior')return parsePrice(b)-parsePrice(a);return Number(a.dataset.order||0)-Number(b.dataset.order||0)});cards.forEach((card)=>grid.appendChild(card))}
function updateResultCount(){const count=Array.from(document.querySelectorAll('[data-catalog-card]')).filter((card)=>!card.hidden).length;document.querySelectorAll('[data-result-count]').forEach((node)=>{node.textContent=`${count} obra${count===1?'':'s'} encontrada${count===1?'':'s'}`})}
function cardMatchesQuery(card,query){const terms=expandCatalogQuery(query);if(!terms.length)return true;const text=normalize(`${card.dataset.search||''} ${card.dataset.tags||''} ${card.textContent||''}`);return terms.every((term)=>text.includes(term))}
function applyCatalogFilters(){const query=document.querySelector('[data-catalog-search]')?.value||'';const activeFilter=normalize(getActiveFilter());document.querySelectorAll('[data-catalog-card]').forEach((card)=>{const text=normalize(`${card.dataset.search||''} ${card.textContent||''}`);const tags=normalize(card.dataset.tags||'');const matchesQuery=cardMatchesQuery(card,query);const matchesFilter=activeFilter==='todos'||tags.includes(activeFilter)||text.includes(activeFilter);card.hidden=!(matchesQuery&&matchesFilter)});sortCatalog();updateResultCount();markCatalogState()}
function clearFilters(){const search=document.querySelector('[data-catalog-search]');const sort=document.querySelector('[data-catalog-sort]');if(search)search.value='';if(sort)sort.value='curadoria';document.querySelectorAll('[data-filter]').forEach((button)=>button.classList.remove('is-active'));document.querySelector('[data-filter="todos"]')?.classList.add('is-active');applyCatalogFilters()}
function hydrateCatalogFromUrl(){const params=new URLSearchParams(window.location.search);const q=params.get('q')||params.get('busca')||'';const filter=params.get('filter')||params.get('filtro')||'';const search=document.querySelector('[data-catalog-search]');if(q&&search)search.value=q; if(filter){document.querySelectorAll('[data-filter]').forEach((button)=>button.classList.remove('is-active'));document.querySelector(`[data-filter="${CSS.escape(filter)}"]`)?.classList.add('is-active')}}
function readLocalArray(key){try{const data=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(data)?data:[]}catch{return[]}}
function markCatalogState(){const saved=readLocalArray('arandu.selection.v1').map((item)=>item.id);const reserved=readLocalArray('arandu.reservations.v1').map((item)=>item.title||item.id);document.querySelectorAll('[data-save-artwork]').forEach((button)=>{if(saved.includes(button.dataset.saveArtwork)){button.textContent='Na seleção';button.classList.add('is-active')}});document.querySelectorAll('[data-reserve-artwork]').forEach((button)=>{if(reserved.includes(button.dataset.reserveTitle)||reserved.includes(button.dataset.reserveArtwork)){button.textContent='Reserva solicitada';button.classList.add('is-active')}})}
async function setupCatalog(){const artworks=await loadArtworkData();renderCatalogFromData(artworks);hydrateCatalogFromUrl();applyCatalogFilters();markCatalogState()}
document.addEventListener('input',(event)=>{if(event.target.matches('[data-catalog-search]'))applyCatalogFilters()});
document.addEventListener('change',(event)=>{if(event.target.matches('[data-catalog-sort]'))applyCatalogFilters()});
document.addEventListener('click',(event)=>{const clear=event.target.closest('[data-clear-catalog]');if(clear){event.preventDefault();clearFilters();return}const filter=event.target.closest('[data-filter]');if(!filter)return;event.preventDefault();document.querySelectorAll('[data-filter]').forEach((button)=>button.classList.remove('is-active'));filter.classList.add('is-active');applyCatalogFilters()});
document.addEventListener('arandu:selection-updated',markCatalogState);
document.addEventListener('DOMContentLoaded',setupCatalog);