(function(){
  const form=document.querySelector('[data-certificate-form]'); if(!form)return;
  const tokenInput=document.querySelector('[data-admin-token]'); const list=document.querySelector('[data-cert-list]'); const statusEl=document.querySelector('[data-certificate-status]'); const tokenKey='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(tokenKey)||'';
  const params=new URLSearchParams(location.search); if(params.get('artwork_id'))form.artwork_id.value=params.get('artwork_id'); if(!form.code.value&&form.artwork_id.value)form.code.value='ARANDU-'+form.artwork_id.value.toUpperCase().replace(/[^A-Z0-9]+/g,'-');
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function token(){const t=tokenInput?.value.trim()||''; if(t)localStorage.setItem(tokenKey,t); return t;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); const item=document.createElement('div');item.className='admin-toast';item.textContent=text;zone.appendChild(item);setTimeout(()=>item.remove(),3500);}
  async function api(path,opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json','x-arandu-admin-token':token(),...(opts.headers||{})}}); const json=await res.json().catch(()=>({})); if(!res.ok||json.ok===false)throw new Error(json.error||'Erro administrativo.'); return json;}
  function values(){const fd=new FormData(form);return Object.fromEntries(fd.entries());}
  async function load(){list.innerHTML='<div class="op-empty"><strong>Carregando</strong><span>Consultando certificados...</span></div>'; const data=await api('/api/admin?panel=certificados'); const rows=data.items||[]; list.innerHTML=rows.length?rows.map(c=>'<article class="admin-row"><div><strong>'+esc(c.code)+'</strong><br><small>'+esc(c.artwork_id||'sem obra')+'</small></div><small>'+esc(c.issued_to||'registro curatorial')+'</small><small>'+esc(c.verification_status)+'</small><div class="admin-actions"><button type="button" data-fill-cert="'+esc(c.code)+'">Editar</button><a class="secondary" href="certificado-imprimivel.html?code='+esc(c.code)+'">Imprimir</a></div></article>').join(''):'<div class="op-empty"><strong>Nenhum certificado</strong><span>Gere o primeiro certificado pelo formulário.</span></div>'; window.__certs=rows;}
  form.addEventListener('submit',async(e)=>{e.preventDefault(); const data=values(); statusEl.textContent='Salvando...'; try{const saved=await api('/api/admin',{method:'POST',body:JSON.stringify({panel:'certificados',data})}); statusEl.textContent='Certificado salvo.'; toast('Certificado salvo.'); await load();}catch(err){statusEl.textContent=err.message;toast(err.message);}});
  list?.addEventListener('click',(e)=>{const b=e.target.closest('[data-fill-cert]'); if(!b)return; const row=(window.__certs||[]).find(c=>c.code===b.dataset.fillCert); if(!row)return; ['code','verification_status','artwork_id','artist_id','issued_to','issued_email','certificate_notes'].forEach(k=>{if(form.elements[k]&&row[k]!==undefined&&row[k]!==null)form.elements[k].value=row[k];});});
  document.querySelector('[data-load-certs]')?.addEventListener('click',()=>load().catch(e=>toast(e.message)));
  document.querySelector('[data-open-print-cert]')?.addEventListener('click',()=>{location.href='certificado-imprimivel.html?code='+encodeURIComponent(form.code.value);});
  document.querySelector('[data-open-verify-cert]')?.addEventListener('click',()=>{location.href='verificar-certificado.html?code='+encodeURIComponent(form.code.value);});
  if(token())load().catch(()=>{});
})();
