(function(){
  const sheet=document.querySelector('[data-certificate-sheet]'); if(!sheet)return;
  const codeInput=document.querySelector('[data-certificate-code]');
  function esc(v){return String(v??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  async function sha(text){const data=new TextEncoder().encode(text);const hash=await crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(hash)).map((b)=>b.toString(16).padStart(2,'0')).join('');}
  async function render(cert={}){const code=(cert.code||codeInput.value||'ARANDU-CERTIFICADO').toUpperCase();const verify=location.origin+'/verificar-certificado.html?code='+encodeURIComponent(code);const hash=cert.certificate_hash||await sha([code,cert.artwork_id,cert.artist_id,cert.issued_to].filter(Boolean).join('|')||code);sheet.innerHTML='<p class="eyebrow">Certificado de autenticidade</p><h1>Arandu</h1><h2>'+esc(cert.artwork_title||cert.artwork_id||'Obra certificada')+'</h2><p>Este documento registra autoria, ficha técnica e validação curatorial vinculada ao código abaixo.</p><div class="admin-proposal-items"><article class="admin-proposal-item"><div class="admin-proposal-thumb"></div><div><p class="eyebrow">Código</p><h2>'+esc(code)+'</h2><p><strong>Status:</strong> '+esc(cert.verification_status||'valid')+'</p><p><strong>Obra:</strong> '+esc(cert.artwork_id||'a confirmar')+'</p><p><strong>Artista:</strong> '+esc(cert.artist_id||'a confirmar')+'</p><p><strong>Emitido para:</strong> '+esc(cert.issued_to||'Registro curatorial')+'</p></div></article></div><section class="certificate-preview"><p class="eyebrow">Verificação pública</p><p>'+esc(verify)+'</p><p><strong>Hash:</strong></p><p style="font-family:monospace;word-break:break-all">'+esc(hash)+'</p><p>Para validar, acesse a URL de verificação pública e confira o código.</p></section>';}
  async function load(){const code=codeInput.value.trim(); if(!code){await render({});return;} const res=await fetch('/api/certificates?code='+encodeURIComponent(code)); const json=await res.json().catch(()=>({})); await render(json.certificate||{code});}
  document.querySelector('[data-load-certificate]')?.addEventListener('click',()=>load()); document.querySelector('[data-print-certificate]')?.addEventListener('click',()=>window.print()); codeInput?.addEventListener('input',()=>render({code:codeInput.value})); render({});
})();
