(function(){
  const form=document.querySelector('[data-collection-editor]'); const list=document.querySelector('[data-collections-admin-list]'); if(!form||!list)return; const key='arandu.collections.draft'; let items=[];
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); const item=document.createElement('div'); item.className='admin-toast'; item.textContent=text; zone.appendChild(item); setTimeout(()=>item.remove(),3500);}
  function save(){localStorage.setItem(key,JSON.stringify(items));}
  function render(){list.innerHTML=items.map(c=>'<article class="af-card"><p class="eyebrow">'+esc(c.id)+'</p><h3>'+esc(c.title)+'</h3><p>'+esc(c.summary)+'</p><div class="admin-actions"><a href="colecao.html?id='+esc(c.id)+'">Ver</a><button type="button" data-edit="'+esc(c.id)+'">Editar</button><button type="button" class="secondary" data-remove="'+esc(c.id)+'">Remover</button></div></article>').join('')||'<p>Nenhuma coleção em edição.</p>';}
  async function load(){try{items=JSON.parse(localStorage.getItem(key)||'[]');}catch{items=[];} if(!items.length){try{items=await fetch('data/collections.json').then(r=>r.json());}catch{items=[];}} render();}
  form.addEventListener('submit',(e)=>{e.preventDefault();const fd=new FormData(form);const c={id:fd.get('id'),title:fd.get('title'),subtitle:fd.get('subtitle'),hero:fd.get('hero'),summary:fd.get('summary'),criteria:String(fd.get('criteria')||'').split('\n').map(x=>x.trim()).filter(Boolean)};items=items.filter(x=>x.id!==c.id).concat(c);save();render();form.reset();toast('Coleção atualizada no rascunho local.');});
  list.addEventListener('click',(e)=>{const edit=e.target.closest('[data-edit]');const remove=e.target.closest('[data-remove]');if(edit){const c=items.find(x=>x.id===edit.dataset.edit);if(c){form.id.value=c.id;form.title.value=c.title;form.subtitle.value=c.subtitle||'';form.hero.value=c.hero||'';form.summary.value=c.summary||'';form.criteria.value=(c.criteria||[]).join('\n');}} if(remove){items=items.filter(x=>x.id!==remove.dataset.remove);save();render();}});
  document.querySelector('[data-copy-collections]')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(JSON.stringify(items,null,2));toast('JSON copiado.');});load();
})();
