(function(){
  const root=document.querySelector('[data-collection-page]'); if(!root)return;
  const id=new URLSearchParams(location.search).get('id')||'primeira';
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function img(w){return w.main_image_url||w.image_url||w.image||'';}
  async function json(url){const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error('Não foi possível carregar a coleção.');return res.json();}
  function card(w){const media=img(w)?'<div class="op-card-media"><img width="640" height="480" loading="lazy" decoding="async" src="'+esc(img(w))+'" alt="'+esc(w.title)+'"></div>':'<div class="op-card-media"></div>';return '<a class="ux-work-card" href="obra.html?id='+esc(w.id)+'">'+media+'<strong>'+esc(w.title)+'</strong><span class="artist">'+esc(w.artist_name||w.artist||'Artista Arandu')+'</span><div class="op-work-foot"><span class="op-price">'+esc(w.price_label||'sob consulta')+'</span><span class="op-mini-link">Ver obra →</span></div></a>';}
  function matches(w,c){const s=JSON.stringify(w).toLowerCase(); if(c.id==='primeira')return Number(w.price||0)<=7000||/fotografia|papel|gravura|primeira/.test(s); if(c.id==='casa')return /casa|sala|apartamento|pintura|fotografia|parede|paisagem/.test(s); if(c.id==='empresa')return /empresa|escritório|escritorio|recepção|recepcao|clínica|clinica|hotel|ambiente|escultura/.test(s); if(c.id==='brasil')return /brasil|território|territorio|rio|sertão|sertao|afro|origin|indígena|indigena|cidade/.test(s); return true;}
  Promise.all([json('data/collections.json'),window.AranduCatalogSource?.catalog()||Promise.reject(new Error('Fonte do catálogo não carregada.'))]).then(([cols,catalog])=>{const c=cols.find(x=>x.id===id)||cols[0];const works=catalog.filter(w=>matches(w,c)).slice(0,12);document.title=c.title+' — Arandu';root.innerHTML='<section class="rect-hero"><div class="container"><div class="breadcrumb public"><a href="index.html">Home</a><span>›</span><a href="colecoes.html">Coleções</a><span>›</span><span>'+esc(c.title)+'</span></div><p class="eyebrow">Coleção curatorial</p><h1 class="title">'+esc(c.title)+'</h1><p class="lead">'+esc(c.hero)+'</p><div class="page-actions"><a class="cta" href="comprar-arte.html?colecao='+esc(c.id)+'">Filtrar no catálogo</a><a class="cta secondary" href="proposta-curatorial.html">Gerar proposta</a></div></div></section><section class="clean-section"><div class="container"><div class="af-grid-2"><article class="af-panel"><p class="eyebrow">Recorte</p><h2>'+esc(c.subtitle)+'</h2><p>'+esc(c.summary)+'</p></article><article class="af-panel"><p class="eyebrow">Critérios</p><ul>'+c.criteria.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></article></div><div class="section-head"><div><p class="eyebrow">Obras</p><h2 class="section-title">Seleção sugerida.</h2></div></div><div class="ux-work-grid">'+(works.length?works.map(card).join(''):'<div class="op-empty"><strong>Nenhuma obra encontrada</strong><span>Use a página Comprar para refinar manualmente.</span></div>')+'</div></div></section>';}).catch((error)=>{const message=window.AranduCatalogSource?.message(error,'acervo')||error.message;root.innerHTML='<section class="clean-section"><div class="container"><div class="op-empty catalog-unavailable"><strong>Coleção em validação curatorial</strong><span>'+esc(message)+'</span>'+(window.AranduCatalogSource?.rescueActions('acervo')||'')+'</div></div></section>';});
})();
