(function(){
  const root=document.querySelector('[data-funnel-output]'); if(!root)return;
  const tokenInput=document.querySelector('[data-admin-token]'); const key='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(key)||'';
  const stages=['new','contacted','qualified','proposal','won','lost'];
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function token(){const t=tokenInput?.value.trim()||''; if(t)localStorage.setItem(key,t); return t;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); const item=document.createElement('div');item.className='admin-toast';item.textContent=text;zone.appendChild(item);setTimeout(()=>item.remove(),3500);}
  async function api(panel){const res=await fetch('/api/admin?panel='+panel,{headers:{'x-arandu-admin-token':token()}});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw new Error(data.error||'Erro no funil.');return data.items||[];}
  function daysSince(date){if(!date)return 999;return Math.floor((Date.now()-new Date(date).getTime())/86400000);}
  async function load(){root.innerHTML='<div class="op-empty"><strong>Carregando</strong><span>Consultando leads, briefings e propostas...</span></div>'; const [leads,briefs,proposals]=await Promise.all([api('leads'),api('briefs'),api('proposals')]); const byStage=Object.fromEntries(stages.map(s=>[s,0])); leads.concat(briefs).forEach(item=>{const st=item.status||'new'; if(byStage[st]!==undefined)byStage[st]++;}); const total=leads.length+briefs.length; const won=byStage.won||0; const sent=proposals.filter(p=>['sent','approved','declined'].includes(p.status)).length; const ticket=proposals.reduce((s,p)=>s+(Number(p.total)||0),0); const stalled=leads.concat(briefs).filter(i=>daysSince(i.updated_at||i.created_at)>7 && !['won','lost','archived'].includes(i.status)).slice(0,12); root.innerHTML='<div class="admin-metrics"><article class="admin-metric"><strong>'+total+'</strong><span>Oportunidades</span></article><article class="admin-metric"><strong>'+sent+'</strong><span>Propostas enviadas</span></article><article class="admin-metric"><strong>'+won+'</strong><span>Ganhos</span></article><article class="admin-metric"><strong>'+ticket.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})+'</strong><span>Total proposto</span></article></div><h2>Etapas</h2><div class="af-funnel">'+stages.map(st=>'<article><span class="af-badge">'+esc(st)+'</span><strong>'+byStage[st]+'</strong><p>'+Math.round((byStage[st]/Math.max(total,1))*100)+'% do funil</p></article>').join('')+'</div><h2>Follow-ups necessários</h2><div class="admin-table">'+(stalled.length?stalled.map(i=>'<article class="admin-row"><div><strong>'+esc(i.name||i.company||i.email||i.id)+'</strong><br><small>'+esc(i.email||i.whatsapp||i.project_type||'')+'</small></div><small>'+esc(i.status)+'</small><small>'+daysSince(i.updated_at||i.created_at)+' dias</small><div class="admin-actions"><a href="lead-detalhe.html?id='+esc(i.id)+'">Abrir</a></div></article>').join(''):'<div class="op-empty"><strong>Nenhum follow-up crítico</strong><span>Sem oportunidades paradas acima de 7 dias.</span></div>')+'</div>'; toast('Funil atualizado.');}
  document.querySelector('[data-load-funnel]')?.addEventListener('click',()=>load().catch(e=>toast(e.message))); if(token())load().catch(()=>{});
})();
