(function(){
  const output=document.querySelector('[data-history-output]'); if(!output)return;
  const tokenInput=document.querySelector('[data-admin-token]'); const idInput=document.querySelector('[data-history-id]'); const tokenKey='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(tokenKey)||''; const params=new URLSearchParams(location.search); if(params.get('id'))idInput.value=params.get('id');
  const isArtist=location.pathname.includes('historico-artista');
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function token(){const t=tokenInput?.value.trim()||''; if(t)localStorage.setItem(tokenKey,t); return t;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); const item=document.createElement('div'); item.className='admin-toast'; item.textContent=text; zone.appendChild(item); setTimeout(()=>item.remove(),3500);}
  async function api(path){const res=await fetch(path,{headers:{'x-arandu-admin-token':token()}});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw new Error(data.error||'Erro ao carregar histórico.');return data;}
  function event(label,date,text,type='info'){return {label,date:date||new Date().toISOString(),text,type};}
  async function load(){const id=idInput.value.trim(); if(!id)throw new Error('Informe um ID.'); output.innerHTML='<div class="op-empty"><strong>Carregando</strong><span>Montando linha do tempo...</span></div>'; const [works,artists,reservations,proposals,certs]=await Promise.all([api('/api/admin?panel=obras'),api('/api/admin?panel=artistas'),api('/api/admin?panel=reservations').catch(()=>({items:[]})),api('/api/admin?panel=proposals').catch(()=>({items:[]})),api('/api/admin?panel=certificados').catch(()=>({items:[]}))]); let events=[]; if(isArtist){const artist=(artists.items||[]).find(a=>String(a.id)===id); if(!artist)throw new Error('Artista não encontrado.'); events.push(event('Artista cadastrado',artist.created_at,'Perfil criado no banco.')); events.push(event('Status atual',artist.updated_at||artist.created_at,'Status: '+(artist.status||'sem status'))); (works.items||[]).filter(w=>w.artist_id===id).forEach(w=>events.push(event('Obra vinculada',w.created_at,w.title+' · '+(w.status||'sem status'))));} else {const work=(works.items||[]).find(w=>String(w.id)===id); if(!work)throw new Error('Obra não encontrada.'); events.push(event('Obra cadastrada',work.created_at,work.title)); events.push(event('Status atual',work.updated_at||work.created_at,'Status: '+(work.status||'sem status'))); if(work.price||work.price_label)events.push(event('Preço registrado',work.updated_at||work.created_at,work.price_label||work.price)); (reservations.items||[]).filter(r=>r.artwork_id===id).forEach(r=>events.push(event('Reserva',r.created_at,(r.name||'Lead')+' · '+(r.status||'requested')))); (certs.items||[]).filter(c=>c.artwork_id===id).forEach(c=>events.push(event('Certificado',c.issued_at||c.created_at,c.code+' · '+(c.verification_status||''))));}
    events.sort((a,b)=>String(b.date).localeCompare(String(a.date))); output.innerHTML=events.map(e=>'<article><p class="eyebrow">'+esc(e.label)+'</p><h3>'+esc(new Date(e.date).toLocaleString('pt-BR'))+'</h3><p>'+esc(e.text)+'</p></article>').join(''); toast('Histórico carregado.');}
  document.querySelector('[data-load-history]')?.addEventListener('click',()=>load().catch(e=>toast(e.message))); if(idInput.value&&tokenInput.value)load().catch(()=>{});
})();
