(function(){
  const tokenInput=document.querySelector('[data-admin-token]'); const idInput=document.querySelector('[data-lead-id]'); const profile=document.querySelector('[data-lead-profile]'); const notes=document.querySelector('[data-lead-notes]'); const tasks=document.querySelector('[data-lead-tasks]'); if(!profile)return;
  const tokenKey='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(tokenKey)||''; const params=new URLSearchParams(location.search); if(params.get('id'))idInput.value=params.get('id'); let currentLead=null;
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function token(){const t=tokenInput?.value.trim()||''; if(t)localStorage.setItem(tokenKey,t); return t;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); const item=document.createElement('div');item.className='admin-toast';item.textContent=text;zone.appendChild(item);setTimeout(()=>item.remove(),3500);}
  async function api(path,opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json','x-arandu-admin-token':token(),...(opts.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw new Error(data.error||'Erro CRM.');return data;}
  async function load(){const id=idInput.value.trim(); if(!id)throw new Error('Informe o ID.'); const data=await api('/api/admin?panel=leads'); currentLead=(data.items||[]).find(l=>String(l.id)===id); if(!currentLead)throw new Error('Lead não encontrado.'); profile.innerHTML='<p class="eyebrow">Lead</p><h2>'+esc(currentLead.name||currentLead.email||currentLead.id)+'</h2><p>'+esc([currentLead.email,currentLead.whatsapp,currentLead.company].filter(Boolean).join(' · '))+'</p><p>'+esc(currentLead.message||'Sem mensagem inicial.')+'</p><div class="admin-actions"><button data-advance-lead>Avançar status</button><a class="secondary" href="proposta-pdf.html">Gerar proposta</a></div>'; await loadOperational(); toast('Lead carregado.');}
  async function loadOperational(){const id=idInput.value.trim(); notes.innerHTML='<p>Notas são salvas no CRM operacional.</p>'; tasks.innerHTML='<p>Tarefas vinculadas ao lead aparecem no painel de tarefas.</p>'; try{const noteData=await api('/api/operational?resource=notes&entity_type=lead&entity_id='+encodeURIComponent(id)); notes.innerHTML=(noteData.items||[]).map(n=>'<article><strong>'+esc(n.author_name||'Curadoria')+'</strong><p>'+esc(n.note)+'</p><small>'+esc(n.created_at||'')+'</small></article>').join('')||'<p>Nenhuma nota.</p>';}catch{} try{const taskData=await api('/api/operational?resource=tasks&entity_type=lead&entity_id='+encodeURIComponent(id)); tasks.innerHTML=(taskData.items||[]).map(t=>'<article><strong>'+esc(t.title)+'</strong><p>'+esc([t.status,t.priority,t.due_at].filter(Boolean).join(' · '))+'</p></article>').join('')||'<p>Nenhuma tarefa.</p>';}catch{}}
  document.querySelector('[data-load-lead]')?.addEventListener('click',()=>load().catch(e=>toast(e.message)));
  document.querySelector('[data-lead-note]')?.addEventListener('submit',async(e)=>{e.preventDefault();const text=e.target.note.value.trim();if(!text)return;await api('/api/operational?resource=notes',{method:'POST',body:JSON.stringify({entity_type:'lead',entity_id:idInput.value.trim(),note:text})});e.target.reset();toast('Nota salva.');loadOperational();});
  document.querySelector('[data-lead-task]')?.addEventListener('submit',async(e)=>{e.preventDefault();await api('/api/operational?resource=tasks',{method:'POST',body:JSON.stringify({entity_type:'lead',entity_id:idInput.value.trim(),title:e.target.title.value,due_at:e.target.due_at.value,priority:e.target.priority.value})});e.target.reset();toast('Tarefa criada.');loadOperational();});
  profile.addEventListener('click',async(e)=>{if(!e.target.closest('[data-advance-lead]')||!currentLead)return;const statuses=['new','contacted','qualified','proposal','won','lost','archived'];const next=statuses[(statuses.indexOf(currentLead.status)+1)%statuses.length]||'contacted';await api('/api/admin',{method:'PATCH',body:JSON.stringify({panel:'leads',id:currentLead.id,status:next})});toast('Lead movido para '+next);load();});
  if(idInput.value&&tokenInput.value)load().catch(()=>{});
})();
