(function(){
  const form=document.querySelector('[data-upload-form]'); if(!form)return;
  const tokenInput=document.querySelector('[data-admin-token]'); const preview=document.querySelector('[data-upload-preview]'); const status=document.querySelector('[data-upload-status]'); const urlInput=document.querySelector('[data-upload-url]'); const tokenKey='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(tokenKey)||'';
  function token(){const value=tokenInput?.value.trim()||''; if(value)localStorage.setItem(tokenKey,value); return value;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); const item=document.createElement('div'); item.className='admin-toast'; item.textContent=text; zone.appendChild(item); setTimeout(()=>item.remove(),3500);}
  function fileToBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});}
  form.file.addEventListener('change',async()=>{const file=form.file.files?.[0]; if(!file)return; const data=await fileToBase64(file); preview.innerHTML='<img src="'+data+'" alt="prévia">';});
  form.addEventListener('submit',async(e)=>{e.preventDefault(); const file=form.file.files?.[0]; if(!file){status.textContent='Selecione uma imagem.';return;} status.textContent='Enviando...'; try{const base64=await fileToBase64(file); const res=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':'application/json','x-arandu-admin-token':token()},body:JSON.stringify({entity_type:form.entity_type.value,entity_id:form.entity_id.value,filename:file.name,content_type:file.type,base64,alt:form.alt.value})}); const json=await res.json().catch(()=>({})); if(!res.ok||json.ok===false)throw new Error(json.error||'Falha no upload.'); urlInput.value=json.url; status.textContent='Imagem enviada. Copie a URL ou use no editor.'; toast('Upload concluído.');}catch(err){status.textContent=err.message; toast(err.message);}});
  document.querySelector('[data-copy-upload-url]')?.addEventListener('click',async()=>{if(!urlInput.value)return; await navigator.clipboard.writeText(urlInput.value); toast('URL copiada.');});
})();
