(function(){
  const sheet=document.querySelector('[data-proposal-sheet]'); if(!sheet)return;
  const client=document.querySelector('[data-proposal-client]'); const space=document.querySelector('[data-proposal-space]'); const goal=document.querySelector('[data-proposal-goal]'); const link=document.querySelector('[data-proposal-link]');
  function esc(v){return String(v??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function items(){try{return JSON.parse(localStorage.getItem('arandu.selection.v1')||'[]');}catch{return[];}}
  function toast(text){let zone=document.querySelector('[data-toast-zone]'); if(!zone){zone=document.createElement('div');zone.className='admin-toast-zone';document.body.appendChild(zone);} const item=document.createElement('div');item.className='admin-toast';item.textContent=text;zone.appendChild(item);setTimeout(()=>item.remove(),3500);}
  function total(list){return list.reduce((sum,item)=>sum+(Number(item.price)||0),0);}
  function render(){const list=items(); const amount=total(list); sheet.innerHTML='<p class="eyebrow">Arandu · proposta curatorial</p><h1>Seleção de arte brasileira contemporânea.</h1><p><strong>Cliente:</strong> '+esc(client.value||'Cliente em análise')+'<br><strong>Ambiente:</strong> '+esc(space.value||'Ambiente a definir')+'<br><strong>Objetivo:</strong> '+esc(goal?.value||'Aquisição com curadoria')+'<br><strong>Data:</strong> '+new Date().toLocaleDateString('pt-BR')+'</p><p>Esta proposta reúne obras salvas em seleção para avaliação curatorial, disponibilidade, documentação, prazo de envio e condições comerciais.</p><div class="admin-proposal-items">'+(list.length?list.map((item,i)=>'<article class="admin-proposal-item"><div class="admin-proposal-thumb '+esc(item.thumb||'')+'"></div><div><p class="eyebrow">Obra '+(i+1)+'</p><h2>'+esc(item.title)+'</h2><p>'+esc(item.artist)+'</p><p>'+esc([item.technique,item.dimensions,item.priceLabel].filter(Boolean).join(' · '))+'</p><p>'+esc(item.context||item.note||'Seleção curatorial Arandu.')+'</p></div></article>').join(''):'<div class="op-empty"><strong>Seleção vazia</strong><span>Salve obras antes de gerar a proposta.</span></div>')+'</div><section class="certificate-preview"><p class="eyebrow">Resumo comercial</p><h2>'+esc(list.length)+' obras selecionadas</h2><p>'+esc(amount?amount.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Valores sob consulta ou em validação.')+'</p><p>A proposta não confirma reserva. A Arandu verifica disponibilidade, certificado, envio e condição antes de qualquer fechamento.</p></section>';}
  async function saveProposal(){const list=items(); if(!list.length){toast('Seleção vazia.');return;} const res=await fetch('/api/proposals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client:client.value,space:space.value,goal:goal?.value,items:list,total:total(list),notes:'Proposta criada pela página proposta-pdf.html'})}); const json=await res.json().catch(()=>({})); if(!res.ok||json.ok===false)throw new Error(json.error||'Erro ao salvar proposta.'); toast('Proposta salva.');}
  async function saveSelection(){const list=items(); if(!list.length){toast('Seleção vazia.');return;} const res=await fetch('/api/selections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:client.value,email:'',items:list,briefing:{space:space.value,goal:goal?.value},source:'proposta-pdf'})}); const json=await res.json().catch(()=>({})); if(!res.ok||json.ok===false)throw new Error(json.error||'Erro ao gerar link.'); const token=json.selection?.public_token||json.selection?.id||''; const url=token?location.origin+'/proposta-publica.html?token='+encodeURIComponent(token):'Seleção salva sem token público.'; if(link)link.value=url; if(token)await navigator.clipboard.writeText(url).catch(()=>{}); toast(token?'Link público copiado.':'Seleção salva.');}
  [client,space,goal].forEach(el=>el?.addEventListener('input',render)); document.querySelector('[data-print-proposal]')?.addEventListener('click',()=>window.print()); document.querySelector('[data-save-proposal]')?.addEventListener('click',()=>saveProposal().catch(e=>toast(e.message))); document.querySelector('[data-save-public-selection]')?.addEventListener('click',()=>saveSelection().catch(e=>toast(e.message))); render();
})();
