(function(){
  const list=document.querySelector('[data-proposals-list]'); if(!list)return; const tokenInput=document.querySelector('[data-admin-token]'); const key='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(key)||'';
  const statuses=['draft','sent','approved','declined','expired','archived'];
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function token(){const t=tokenInput?.value.trim()||''; if(t)localStorage.setItem(key,t); return t;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); const item=document.createElement('div'); item.className='admin-toast'; item.textContent=text; zone.appendChild(item); setTimeout(()=>item.remove(),3500);}
  async function api(path,opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json','x-arandu-admin-token':token(),...(opts.headers||{})}}); const json=await res.json().catch(()=>({})); if(!res.ok||json.ok===false)throw new Error(json.error||'Erro em propostas.'); return json;}
  async function load(){list.innerHTML='<div class="op-empty"><strong>Carregando</strong><span>Consultando propostas...</span></div>'; const data=await api('/api/admin?panel=proposals'); const rows=data.items||[]; list.innerHTML=rows.length?rows.map(p=>'<article class="admin-row"><div><strong>'+esc(p.client||p.id)+'</strong><br><small>'+esc([p.space,p.goal].filter(Boolean).join(' · '))+'</small></div><small>'+esc((Number(p.total)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}))+'</small><small>'+esc(p.status||'draft')+'</small><div class="admin-actions"><button data-next-proposal="'+esc(p.id)+'">Avançar</button><a class="secondary" href="editor-registro.html?panel=proposals&id='+esc(p.id)+'">Editar</a></div></article>').join(''):'<div class="op-empty"><strong>Nenhuma proposta</strong><span>Gere propostas pela página de PDF.</span></div>'; window.__proposals=rows;}
  list.addEventListener('click',async(e)=>{const b=e.target.closest('[data-next-proposal]'); if(!b)return; const p=(window.__proposals||[]).find(x=>String(x.id)===b.dataset.nextProposal); if(!p)return; const next=statuses[(statuses.indexOf(p.status)+1)%statuses.length]||'sent'; await api('/api/admin',{method:'PATCH',body:JSON.stringify({panel:'proposals',id:p.id,status:next})}); toast('Proposta movida para '+next); load();});
  document.querySelector('[data-load-proposals]')?.addEventListener('click',()=>load().catch(e=>toast(e.message))); if(token())load().catch(()=>{});
})();
