(function(){
  const form=document.querySelector('[data-record-editor]'); if(!form)return;
  const tokenInput=document.querySelector('[data-admin-token]'); const statusEl=document.querySelector('[data-editor-status]'); const tokenKey='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(tokenKey)||'';
  const params=new URLSearchParams(location.search); form.panel.value=params.get('panel')||'obras'; form.id.value=params.get('id')||'';
  function esc(v){return String(v??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function token(){const t=tokenInput?.value.trim()||''; if(t)localStorage.setItem(tokenKey,t); return t;}
  function toast(text){let zone=document.querySelector('[data-toast-zone]'); if(!zone){zone=document.createElement('div');zone.className='admin-toast-zone';document.body.appendChild(zone);} const item=document.createElement('div');item.className='admin-toast';item.textContent=text;zone.appendChild(item);setTimeout(()=>item.remove(),3500);}
  async function api(path,opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json','x-arandu-admin-token':token(),...(opts.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw new Error(data.error||'Erro administrativo.');return data;}
  function fill(item){if(!item)return; const map={title:item.title||item.name||item.code,status:item.status||item.verification_status,technique:item.technique||((item.languages||[]).join(', ')),price:item.price,price_label:item.price_label,city:item.city,state:item.state,main_image_url:item.main_image_url||item.image_url,image_url:item.image_url,tags:(item.tags||item.languages||[]).join(', '),summary:item.summary||item.profile,curatorial_reading:item.curatorial_reading||item.trajectory}; Object.entries(map).forEach(([k,v])=>{if(form.elements[k]&&v!==undefined&&v!==null)form.elements[k].value=v;});}
  async function load(){const panel=form.panel.value; const id=form.id.value.trim(); if(!id)return; statusEl.textContent='Carregando...'; const data=await api('/api/admin?panel='+encodeURIComponent(panel)); const item=(data.items||[]).find((row)=>String(row.id||row.code)===id); if(!item){statusEl.textContent='Registro não encontrado.';return;} fill(item); statusEl.textContent='Registro carregado.'; toast('Registro carregado.');}
  function fields(){const fd=new FormData(form); const panel=fd.get('panel'); const values=Object.fromEntries(fd.entries()); delete values.panel; delete values.id; const f={}; Object.entries(values).forEach(([k,v])=>{if(v!==''&&v!==null)f[k]=v;}); if(panel==='artistas'){if(f.title){f.name=f.title;delete f.title;} if(f.technique){f.languages=f.technique;delete f.technique;} if(f.curatorial_reading){f.trajectory=f.curatorial_reading;delete f.curatorial_reading;} if(f.tags){f.curatorial_axes=f.tags;delete f.tags;} delete f.price; delete f.price_label; delete f.main_image_url;}
    if(panel==='obras'){if(f.image_url&&!f.main_image_url)f.main_image_url=f.image_url; delete f.image_url; delete f.city; delete f.state;}
    return {panel,id:fd.get('id'),fields:f};}
  form.addEventListener('submit',async(e)=>{e.preventDefault(); const body=fields(); if(!body.id){statusEl.textContent='Informe um ID.';return;} statusEl.textContent='Salvando...'; try{const data=await api('/api/admin-update',{method:'PATCH',body:JSON.stringify(body)}); statusEl.textContent='Alterações salvas.'; toast('Alterações salvas.');}catch(err){statusEl.textContent=err.message; toast(err.message);}});
  document.querySelector('[data-load-record]')?.addEventListener('click',()=>load().catch(e=>toast(e.message)));
  document.querySelector('[data-open-public]')?.addEventListener('click',()=>{const panel=form.panel.value,id=form.id.value.trim(); if(!id)return; location.href=(panel==='artistas'?'artista.html?id=':'obra.html?id=')+encodeURIComponent(id);});
  if(form.id.value&&tokenInput.value)load().catch(()=>{});
})();
