(function(){
  const board=document.querySelector('[data-kanban-board]'); if(!board)return;
  const tokenInput=document.querySelector('[data-admin-token]');
  const sourceSelect=document.querySelector('[data-kanban-source]');
  const search=document.querySelector('[data-kanban-search]');
  const key='arandu.admin.token'; if(tokenInput)tokenInput.value=localStorage.getItem(key)||'';
  const statusMap={leads:['new','contacted','qualified','proposal','reserved','won','lost'],briefs:['received','qualified','proposal','negotiation','won','lost'],reservations:['requested','confirmed','expired','cancelled','converted'],proposals:['draft','sent','approved','declined','expired','archived']};
  const state={panel:'leads',items:[],statuses:[],term:'',mode:'demo'};
  function esc(v){return String(v??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function token(){const t=tokenInput?.value.trim()||''; if(t)localStorage.setItem(key,t); return t;}
  function toast(text){const zone=document.querySelector('[data-toast-zone]'); if(!zone)return; const item=document.createElement('div');item.className='admin-toast';item.textContent=text;zone.appendChild(item);setTimeout(()=>item.remove(),3500);}
  async function api(path,opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json','x-arandu-admin-token':token(),...(opts.headers||{})}}); const json=await res.json().catch(()=>({})); if(!res.ok||json.ok===false)throw new Error(json.error||'Erro no kanban.'); return json;}
  function demo(panel){return ({leads:[{id:'lead-01',name:'Comprador primeira obra',email:'cliente@email.com',status:'new',message:'Busca obra até R$ 3.000.'},{id:'lead-02',name:'Arquiteta parceira',email:'studio@email.com',status:'contacted',message:'Quer seleção para apartamento.'},{id:'lead-03',name:'Clínica Horizonte',email:'contato@clinica.com',status:'proposal',message:'Recepção e sala de espera.'}],briefs:[{id:'brief-01',company:'Escritório corporativo',status:'received',project_type:'Recepção',budget:'R$ 20.000'},{id:'brief-02',company:'Apartamento em Niterói',status:'proposal',project_type:'Sala',budget:'R$ 6.000'}],reservations:[{id:'res-01',name:'Cliente reserva',artwork_id:'estudo-de-solo-04',status:'requested',notes:'Confirmar disponibilidade com artista.'}],proposals:[{id:'prop-01',client:'Clínica Horizonte',space:'Recepção',status:'draft',total:12000},{id:'prop-02',client:'Apartamento em Niterói',space:'Sala',status:'sent',total:6000}]}[panel]||[]);}
  function label(item){return item.name||item.client||item.company||item.email||item.artwork_id||item.id||'Registro';}
  function status(item){return item.status||item.verification_status||'sem status';}
  function text(item){return JSON.stringify(item).toLowerCase();}
  function render(){const items=state.items.filter((item)=>!state.term||text(item).includes(state.term)); board.innerHTML='<div class="admin-toolbar"><span class="af-badge">Modo '+esc(state.mode)+'</span><span>'+items.length+' registros</span></div>'+state.statuses.map((st)=>{const group=items.filter((item)=>status(item)===st); return '<section class="admin-kanban-column"><h3>'+esc(st)+' <small>'+group.length+'</small></h3>'+group.map((item)=>'<article class="admin-kanban-card"><strong>'+esc(label(item))+'</strong><small>'+esc(item.email||item.whatsapp||item.space||item.project_type||item.id||'')+'</small><p>'+esc(item.message||item.notes||item.budget||item.deadline||'Sem observação.')+'</p><div class="admin-actions"><button type="button" data-next="'+esc(item.id)+'">Avançar</button><a class="secondary" href="editor-registro.html?panel='+esc(state.panel)+'&id='+esc(item.id)+'">Editar</a></div></article>').join('')+'</section>';}).join('');}
  async function load(){state.panel=sourceSelect.value; board.innerHTML='<div class="op-empty"><strong>Carregando</strong><span>Consultando pipeline...</span></div>'; if(token()){try{const data=await api('/api/admin?panel='+encodeURIComponent(state.panel));state.items=data.items||[];state.statuses=data.statusOptions||statusMap[state.panel]||[];state.mode='supabase';render();toast('Kanban carregado.');return;}catch(error){toast('Modo demo: '+error.message);}} state.items=demo(state.panel);state.statuses=statusMap[state.panel]||[];state.mode='demo';render();}
  async function next(id){const item=state.items.find((row)=>String(row.id)===String(id)); if(!item)return; const current=status(item); const nextStatus=state.statuses[(state.statuses.indexOf(current)+1)%state.statuses.length]||state.statuses[0]; if(state.mode==='supabase'){await api('/api/admin',{method:'PATCH',body:JSON.stringify({panel:state.panel,id,status:nextStatus})}); await load();}else{item.status=nextStatus;render();} toast('Movido para '+nextStatus);}
  document.querySelector('[data-load-kanban]')?.addEventListener('click',()=>load().catch(e=>toast(e.message)));
  sourceSelect?.addEventListener('change',()=>load().catch(e=>toast(e.message)));
  search?.addEventListener('input',()=>{state.term=search.value.toLowerCase();render();});
  board.addEventListener('click',(e)=>{const b=e.target.closest('[data-next]'); if(b)next(b.dataset.next).catch(err=>toast(err.message));});
  load().catch(()=>{});
})();
