const ARANDU_BRIEFING_KEY = 'arandu.selection.briefing.v1';
const ARANDU_SELECTION_KEY = 'arandu.selection.v1';

function getStoredSelection(){try{const data=JSON.parse(localStorage.getItem(ARANDU_SELECTION_KEY)||'[]');return Array.isArray(data)?data:[]}catch{return[]}}
function writeStoredSelection(items){localStorage.setItem(ARANDU_SELECTION_KEY,JSON.stringify(Array.isArray(items)?items.slice(-40):[]));document.dispatchEvent(new CustomEvent('arandu:selection-updated'))}
function getStoredBriefing(){try{return JSON.parse(localStorage.getItem(ARANDU_BRIEFING_KEY)||'{}')}catch{return{}}}
function writeStoredBriefing(data){localStorage.setItem(ARANDU_BRIEFING_KEY,JSON.stringify(data))}
function escapeHtml(value){return String(value||'').replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function briefingLines(){const briefing=getStoredBriefing();const labels={ambiente:'Ambiente',orcamento:'Orçamento',prazo:'Prazo',dimensao:'Dimensão / parede',sensacao:'Sensação desejada',uso:'Uso do espaço',observacoes:'Observações'};return Object.entries(labels).map(([key,label])=>briefing[key]?`${label}: ${briefing[key]}`:'').filter(Boolean)}
function itemLine(item,index){const price=item.priceLabel?`\n   Valor: ${item.priceLabel}`:'';const tech=item.technique?`\n   Técnica: ${item.technique}`:'';const dims=item.dimensions?`\n   Dimensões: ${item.dimensions}`:'';return `${index+1}. ${item.title} — ${item.artist}${price}${tech}${dims}\n   Contexto: ${item.context}\n   Observação: ${item.note||'sem observação'}\n   Link: ${item.url||'obras.html'}`}
function buildSelectionPlainText(){const items=getStoredSelection();const briefing=briefingLines();const works=items.length?items.map(itemLine).join('\n\n'):'Nenhuma obra salva ainda.';return `Briefing Arandu\n\n${briefing.length?briefing.join('\n'):'Contexto ainda não preenchido.'}\n\nObras selecionadas:\n${works}`}
function buildSelectionDocument(){const items=getStoredSelection();const briefing=briefingLines();const briefingHtml=briefing.length?briefing.map((line)=>`<p>${escapeHtml(line)}</p>`).join(''):'<p>Contexto ainda não preenchido.</p>';const rows=items.length?items.map((item,index)=>`<tr><td>${index+1}</td><td>${escapeHtml(item.title)}</td><td>${escapeHtml(item.artist)}</td><td>${escapeHtml(item.priceLabel||'')}</td><td>${escapeHtml(item.technique||'')}</td><td>${escapeHtml(item.dimensions||'')}</td><td>${escapeHtml(item.context)}</td><td>${escapeHtml(item.note||'')}</td></tr>`).join(''):'<tr><td colspan="8">Nenhuma obra salva.</td></tr>';return `<!doctype html><html><head><meta charset="UTF-8"><title>Seleção Arandu</title><style>body{font-family:Arial,sans-serif;background:#efe3d1;color:#211713;padding:42px}h1,h2{font-family:Georgia,serif;color:#5a1f1a}p{line-height:1.6}table{width:100%;border-collapse:collapse;background:#f7ead9;border-radius:18px;overflow:hidden}td,th{border:1px solid #ad8a62;padding:12px;text-align:left}.note{background:#173f31;color:#f7ead9;padding:22px;border-radius:18px;margin:22px 0}.note p{color:#f7ead9}</style></head><body><h1>Minha seleção Arandu</h1><div class="note"><h2>Briefing</h2>${briefingHtml}</div><p>Seleção criada para conversa com a curadoria. Compare presença, linguagem, escala, orçamento e intenção antes de decidir.</p><table><tr><th>#</th><th>Obra</th><th>Artista</th><th>Valor</th><th>Técnica</th><th>Dimensão</th><th>Contexto</th><th>Observação</th></tr>${rows}</table></body></html>`}
function downloadSelectionHtml(){const blob=new Blob([buildSelectionDocument()],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='selecao-arandu.html';document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
function getSelectionTerms(items){const text=items.map((item)=>`${item.title} ${item.artist} ${item.context} ${item.note||''} ${item.technique||''} ${item.dimensions||''}`).join(' ').toLowerCase();const map=[['matéria e terra',['terra','solo','matéria','pintura','óleo','argila']],['memória e território',['memória','sertão','botânica','silêncio','território']],['movimento urbano',['movimento','urbana','ritmo','cidade']],['fotografia de entrada',['fotografia','fine art','imagem']],['escultura e volume',['escultura','bronze','objeto','volume']],['tons terrosos',['solo','terra','outono','ocre','barro']]];return map.filter(([,words])=>words.some((word)=>text.includes(word))).map(([label])=>label)}
function selectionReadiness(items){const briefing=getStoredBriefing();let score=0;const reasons=[];if(items.length>=1){score+=20;reasons.push('há ao menos uma obra salva')}if(items.length>=2){score+=20;reasons.push('há comparação possível entre obras')}if(briefing.ambiente){score+=15;reasons.push('ambiente informado')}if(briefing.orcamento){score+=15;reasons.push('orçamento informado')}if(briefing.sensacao){score+=10;reasons.push('sensação desejada definida')}if(briefing.prazo){score+=10;reasons.push('prazo informado')}if(items.some((item)=>item.note)){score+=10;reasons.push('há observações nas obras')}return{score:Math.min(score,100),reasons}}
function inferNextStep(items,terms){const briefing=getStoredBriefing();if(!briefing.ambiente||!briefing.orcamento)return'complete ambiente e orçamento para transformar a seleção em briefing de curadoria.';if(items.length<2)return'salve ao menos mais uma obra para comparar linguagem e presença.';if(terms.includes('fotografia de entrada'))return'compare fotografia com pintura pequena para decidir entre narrativa e matéria.';if(terms.includes('escultura e volume'))return'confira escala, base de apoio e circulação do ambiente antes de reservar.';if(terms.includes('matéria e terra'))return'observe como tons, textura e dimensão conversam com a luz do espaço.';return'compare linguagem, escala e faixa de preço antes de decidir.'}
function renderCuratorialReading(){const target=document.querySelector('[data-curatorial-reading]');if(!target)return;const items=getStoredSelection();if(!items.length){target.innerHTML='<article class="selection-reading-card"><p class="eyebrow">Leitura curatorial automática</p><h3>Salve obras para formar uma leitura.</h3><p>Com duas ou três obras, a seleção começa a revelar preferências de linguagem, presença, matéria e orçamento.</p><div class="page-actions"><a class="cta secondary" href="obras.html">Ver acervo</a><a class="cta secondary" href="pesquisa.html">Pesquisar</a></div></article>';return}const terms=getSelectionTerms(items);const safeTerms=terms.length?terms:['interesse inicial','curiosidade visual','seleção em formação'];const nextStep=inferNextStep(items,safeTerms);const readiness=selectionReadiness(items);target.innerHTML=`<article class="selection-reading-card"><p class="eyebrow">Leitura curatorial automática</p><h3>Sua seleção indica interesse por:</h3><div class="reading-list">${safeTerms.map((term)=>`<span>${escapeHtml(term)}</span>`).join('')}</div><p><strong>Prontidão da seleção:</strong> ${readiness.score}%</p><div class="reading-list">${readiness.reasons.map((reason)=>`<span>${escapeHtml(reason)}</span>`).join('')}</div><p><strong>Caminho recomendado:</strong> ${escapeHtml(nextStep)}</p><p>Use esta leitura como ponto de partida. A decisão final deve considerar ambiente, luz, escala, trajetória do artista e o tipo de presença desejada.</p><div class="page-actions"><a class="cta secondary" href="comparar-obras.html">Comparar caminhos</a><a class="cta secondary" href="proposta-curatorial.html">Gerar proposta</a><a class="cta secondary" href="pesquisa.html">Pesquisar semelhantes</a></div></article>`}
function renderSelectionComparison(){const target=document.querySelector('[data-selection-comparison]');if(!target)return;const items=getStoredSelection();if(!items.length){target.innerHTML='<p>Salve obras para comparar sua seleção.</p>';return}target.innerHTML=`<div class="grid grid-3">${items.map((item)=>`<article class="card"><span class="tag">${escapeHtml(item.status||'Selecionada')}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.artist)}</p><p>${escapeHtml([item.priceLabel,item.technique,item.dimensions].filter(Boolean).join(' · '))}</p><p>${escapeHtml(item.context)}</p><p>${escapeHtml(item.note||'Adicione uma observação para orientar a curadoria.')}</p><div class="page-actions"><a class="cta secondary" href="${escapeHtml(item.url||'obras.html')}">Ver obra</a><button class="cta secondary" type="button" data-reserve-artwork="${escapeHtml(item.id)}" data-reserve-title="${escapeHtml(item.title)}" data-reserve-artist="${escapeHtml(item.artist)}" data-reserve-url="${escapeHtml(item.url||'obras.html')}">Reservar com curadoria</button></div></article>`).join('')}</div>`}
function syncBriefingForm(){const form=document.querySelector('[data-briefing-form]');if(!form)return;const stored=getStoredBriefing();form.querySelectorAll('[data-briefing-field]').forEach((field)=>{if(stored[field.name])field.value=stored[field.name]});renderBriefingPreview()}
function readBriefingForm(){const form=document.querySelector('[data-briefing-form]');if(!form)return getStoredBriefing();const data={};form.querySelectorAll('[data-briefing-field]').forEach((field)=>{data[field.name]=field.value.trim()});writeStoredBriefing(data);renderBriefingPreview();renderCuratorialReading();return data}
function renderBriefingPreview(){const target=document.querySelector('[data-briefing-preview]');if(!target)return;const lines=briefingLines();target.innerHTML=`<h3>${lines.length?'Briefing pronto para curadoria':'Briefing em formação'}</h3>${lines.length?lines.map((line)=>`<p>${escapeHtml(line)}</p>`).join(''):'<p>Preencha ambiente, orçamento e intenção para criar uma mensagem curatorial mais completa.</p>'}`}
function selectionSharePayload(){return{items:getStoredSelection(),briefing:getStoredBriefing(),createdAt:new Date().toISOString(),source:'minha-selecao'}}
function encodeSelectionShare(){const payload=JSON.stringify(selectionSharePayload());return btoa(unescape(encodeURIComponent(payload))).replace(/=+$/,'')}
function decodeSelectionShare(value){try{const padded=value+'='.repeat((4-value.length%4)%4);return JSON.parse(decodeURIComponent(escape(atob(padded))))}catch{return null}}
async function saveSelectionRemote(){const response=await fetch('/api/selections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(selectionSharePayload())});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok===false)throw new Error(data.error||'Não foi possível salvar a seleção.');return data}
async function loadSelectionRemote(token){const response=await fetch(`/api/selections?token=${encodeURIComponent(token)}`);const data=await response.json().catch(()=>({}));if(!response.ok||data.ok===false)throw new Error(data.error||'Não foi possível carregar a seleção.');return data.selection||null}
async function copySelectionShareLink(){const items=getStoredSelection();if(!items.length){alert('Salve ao menos uma obra antes de compartilhar.');return}const url=new URL(location.href);try{const data=await saveSelectionRemote();if(data.selection?.public_token){url.searchParams.delete('selection');url.searchParams.set('selection_token',data.selection.public_token)}else{url.searchParams.set('selection',encodeSelectionShare())}}catch{url.searchParams.set('selection',encodeSelectionShare())}url.hash='obras-salvas';try{await navigator.clipboard.writeText(url.toString());document.querySelectorAll('[data-share-selection]').forEach((button)=>{button.textContent='Link copiado'})}catch{prompt('Copie o link da seleção:',url.toString())}}
async function importSelectionFromUrl(){const params=new URLSearchParams(location.search);const token=params.get('selection_token');if(token){try{const remote=await loadSelectionRemote(token);if(remote&&Array.isArray(remote.items)){writeStoredSelection(remote.items);if(remote.briefing&&typeof remote.briefing==='object')writeStoredBriefing(remote.briefing);history.replaceState(null,'',location.pathname+'#obras-salvas');return}}catch{}}
const value=params.get('selection');if(!value)return;const data=decodeSelectionShare(value);if(!data||!Array.isArray(data.items))return;writeStoredSelection(data.items);if(data.briefing&&typeof data.briefing==='object')writeStoredBriefing(data.briefing);history.replaceState(null,'',location.pathname+'#obras-salvas')}
function addShareButton(){const actions=document.querySelector('.selection-actions');if(!actions||actions.querySelector('[data-share-selection]'))return;const button=document.createElement('button');button.className='button secondary';button.type='button';button.dataset.shareSelection='true';button.textContent='Compartilhar link';actions.insertBefore(button,actions.firstChild)}
async function copyBriefing(){readBriefingForm();const text=buildSelectionPlainText();try{await navigator.clipboard.writeText(text);document.querySelectorAll('[data-copy-briefing]').forEach((button)=>{button.textContent='Briefing copiado'})}catch{alert(text)}}
document.addEventListener('input',(event)=>{if(event.target.closest('[data-briefing-field]'))readBriefingForm()});
document.addEventListener('change',(event)=>{if(event.target.closest('[data-briefing-field]'))readBriefingForm()});
document.addEventListener('click',(event)=>{if(event.target.closest('[data-download-selection]')){event.preventDefault();downloadSelectionHtml()}if(event.target.closest('[data-show-selection-comparison]')){event.preventDefault();renderSelectionComparison();renderCuratorialReading()}if(event.target.closest('[data-copy-briefing]')){event.preventDefault();copyBriefing()}if(event.target.closest('[data-share-selection]')){event.preventDefault();copySelectionShareLink()}});
document.addEventListener('arandu:selection-updated',()=>{renderSelectionComparison();renderCuratorialReading()});
document.addEventListener('DOMContentLoaded',async()=>{await importSelectionFromUrl();addShareButton();syncBriefingForm();renderSelectionComparison();renderCuratorialReading()});
