import {test,expect} from '@playwright/test';
import {presentPerformancePage,presentPerformanceDetail} from '../../lib/finance/performance-presenter.mjs';
const ID='00000000-0000-4000-8000-000000000001';
const p={id:ID,contract_id:ID,organization_id:ID,provider_id:ID,title:'Performance teste',status:'open',version:1,period_start:'2026-09-01',period_end:'2026-09-30',review_due_on:'2026-10-05'};
const metrics=[{dimension_id:ID,dimension_title:'SLA contratual',metric:'sla_adherence',unit:'percent',actual:null,target_met:null,availability:'not_available',observation_id:ID,review_id:null}];
async function setup(page,role='admin',status='open'){
 await page.route('**/api/finance/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/api/finance/','');let data={rows:[]};if(path==='organizations')data={rows:[{id:ID,kind:'BUYER',legal_name:'Teste'}]};if(path==='overview')data={organization:{id:ID,kind:'BUYER',legal_name:'Teste'},providers:[],contracts:[],rfqs:[],tasks:[]};if(path==='members')data={rows:[{user_id:'u1',role}],viewer_id:'u1'};if(path==='entities')data={rows:[],scope:'group',can_admin:role==='admin'};if(path==='performance')data=presentPerformancePage({rows:[p],contracts:[],dimensions:[],members:[],next:null});if(path==='performance/detail')data=presentPerformanceDetail({period:{...p,status},metrics,observations:[],reviews:[]});await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,...data})});});
}
test('indisponibilidade não oferece confirmação de medição',async({page})=>{await setup(page);await page.goto(`/finance/performance.html?id=${ID}`);await page.getByRole('dialog').getByRole('button',{name:'Revisar: SLA contratual'}).click();const options=await page.getByRole('dialog').last().getByLabel('Conclusão').locator('option').allTextContents();expect(options).toEqual(['Indisponibilidade confirmada','Rejeitar']);});
test('viewer lê evidência sem registrar ou revisar',async({page})=>{await setup(page,'viewer');await page.goto(`/finance/performance.html?id=${ID}`);await expect(page.getByRole('dialog').getByText(/comparação desconhecida/)).toBeVisible();await expect(page.getByRole('button',{name:'Revisar: SLA contratual'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1);});
test('período fechado preserva histórico sem ações de alteração',async({page})=>{await setup(page,'admin','closed');await page.goto(`/finance/performance.html?id=${ID}`);await expect(page.getByRole('dialog').getByText(/Encerrado/)).toBeVisible();await expect(page.getByRole('button',{name:'Fechar período'})).toHaveCount(0);});
