import {test,expect} from '@playwright/test';
import {presentCovenantPage,presentCovenantDetail} from '../../lib/finance/covenant-presenter.mjs';
const ID='00000000-0000-4000-8000-000000000001';
const p={id:ID,obligation_id:ID,contract_id:ID,organization_id:ID,title:'Covenant teste',kind:'financial_covenant',source_clause:'Cláusula 10.2',period_start:'2026-09-01',period_end:'2026-09-30',due_on:'2026-10-05',facts:{status:'awaiting_data',has_data:false,metric:'Alavancagem',operator:'le',threshold:3,unit:'ratio',measured_value:null,factual_result:null,observed_at:'2026-10-05',formula:'valor <= limiar contratual'}};
async function setup(page,role='admin'){
 await page.route('**/api/finance/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/api/finance/','');let data={rows:[]};if(path==='organizations')data={rows:[{id:ID,kind:'BUYER',legal_name:'Teste'}]};if(path==='overview')data={organization:{id:ID,kind:'BUYER',legal_name:'Teste'},providers:[],contracts:[],rfqs:[],tasks:[]};if(path==='members')data={rows:[{user_id:'u1',role}],viewer_id:'u1'};if(path==='entities')data={rows:[],scope:'group',can_admin:role==='admin'};if(path==='covenants')data=presentCovenantPage({rows:[p],contracts:[],members:[],next:null});if(path==='covenants/detail')data=presentCovenantDetail({period:p,measurements:[],evidence:[],reviews:[],waivers:[]});await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,...data})});});
}
test('dados ausentes não oferecem conclusão de conformidade',async({page})=>{await setup(page);await page.goto(`/finance/covenants.html?id=${ID}`);const d=page.getByRole('dialog');await expect(d.getByText(/Aguardando dados/)).toBeVisible();await expect(d.getByText(/dados ausentes/)).toBeVisible();await d.getByRole('button',{name:'Revisar período'}).click();const options=await page.getByRole('dialog').last().getByLabel('Conclusão').locator('option').allTextContents();expect(options.some(x=>/^Conforme/.test(x))).toBe(false);});
test('viewer lê cláusula e período sem ações de revisão',async({page})=>{await setup(page,'viewer');await page.goto(`/finance/covenants.html?id=${ID}`);await expect(page.getByRole('dialog').getByText('Cláusula: Cláusula 10.2')).toBeVisible();await expect(page.getByRole('button',{name:'Revisar período'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1);});
