import {test,expect} from '@playwright/test';
import {presentSpendPage,presentSpendDetail} from '../../lib/finance/spend-presenter.mjs';
const ID='00000000-0000-4000-8000-000000000001';
const row={id:ID,contract_id:ID,organization_id:ID,provider_id:ID,value_kind:'observed',currency:'BRL',amount:'100.00',source_table:'fin_spend_records',source_id:ID,source_reference:'Arquivo 001',source_line:'1',reconciliation_status:'unreviewed',included:false,period_start:'2026-09-01',period_end:'2026-09-30'};
async function setup(page,role='admin',source='fin_spend_records'){
 await page.route('**/api/finance/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/api/finance/','');let data={rows:[]};if(path==='organizations')data={rows:[{id:ID,kind:'BUYER',legal_name:'Teste'}]};if(path==='overview')data={organization:{id:ID,kind:'BUYER',legal_name:'Teste'},providers:[],contracts:[],rfqs:[],tasks:[]};if(path==='members')data={rows:[{user_id:'u1',role}],viewer_id:'u1'};if(path==='entities')data={rows:[],scope:'group',can_admin:role==='admin'};if(path==='spend')data=presentSpendPage({rows:[row],contracts:[],summary:{rows:[{currency:'BRL',value_kind:'observed',amount:null,included_records:0,records:1,outside_complete_period:0}]},next:null});if(path==='spend/detail')data=presentSpendDetail({row:{...row,source_table:source},history:[],reviews:[]});await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,...data})});});
}
test('reconciliação exige confirmação explícita de duplicatas',async({page})=>{await setup(page);await page.goto(`/finance/spend.html?id=${ID}`);await page.getByRole('dialog').getByRole('button',{name:'Reconciliar',exact:true}).click();await expect(page.getByRole('dialog').last().getByLabel('Comparou com tarifas e outras fontes?')).toHaveValue('false');});
test('viewer inspeciona origem sem alterações e sem overflow',async({page})=>{await setup(page,'viewer');await page.goto(`/finance/spend.html?id=${ID}`);await expect(page.getByRole('dialog').getByText(/Arquivo 001/)).toBeVisible();await expect(page.getByRole('button',{name:'Reconciliar',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1);});
test('evidência derivada de tarifa é somente leitura',async({page})=>{await setup(page,'admin','fin_fee_observations');await page.goto(`/finance/spend.html?id=${ID}`);await expect(page.getByRole('dialog').getByText(/Tarifa observada/)).toBeVisible();await expect(page.getByRole('button',{name:'Corrigir registro'})).toHaveCount(0);});
