export const INTERNAL_PAGES = Object.freeze([
  'admin-preview.html',
  'admin.html',
  'artista-editor.html',
  'benchmark-conversao.html',
  'calendario-editorial.html',
  'catalogo-intake.html',
  'certificados-admin.html',
  'certificado-imprimivel.html',
  'checklist-lancamento.html',
  'colecoes-admin.html',
  'configuracao.html',
  'demo.html',
  'diagnostico-catalogo.html',
  'dominio-go-live.html',
  'editor-registro.html',
  'funil-comercial.html',
  'go-live.html',
  'historico-artista.html',
  'historico-obra.html',
  'kanban-comercial.html',
  'lancamento.html',
  'lead-detalhe.html',
  'mvp-operacional.html',
  'obra-editor.html',
  'onboarding-artista.html',
  'operacao-obras.html',
  'operacao.html',
  'painel-admin.html',
  'painel-artistas.html',
  'painel-briefings.html',
  'painel-cadastros.html',
  'painel-certificados.html',
  'painel-leads.html',
  'painel-mvp.html',
  'painel-obras.html',
  'painel-pedidos.html',
  'painel-piloto.html',
  'painel-propostas.html',
  'painel-qualidade.html',
  'painel-reservas.html',
  'painel-submissoes.html',
  'painel-tarefas.html',
  'painel.html',
  'piloto.html',
  'propostas-admin.html',
  'proposta-pdf.html',
  'prospeccao-artistas.html',
  'revisao-catalogo.html',
  'status.html',
  'templates-comunicacao.html',
  'upload-imagens.html'
]);

export const INTERNAL_PAGE_SET = new Set(INTERNAL_PAGES);

const PAGE_PERMISSIONS = Object.freeze({
  'admin-preview.html': ['dashboard', 'read'],
  'admin.html': ['dashboard', 'read'],
  'artista-editor.html': ['artists', 'update'],
  'benchmark-conversao.html': ['commercial', 'read'],
  'calendario-editorial.html': ['artworks', 'read'],
  'catalogo-intake.html': ['artworks', 'create'],
  'certificados-admin.html': ['certificates', 'read'],
  'certificado-imprimivel.html': ['certificates', 'read'],
  'checklist-lancamento.html': ['diagnostics', 'read'],
  'colecoes-admin.html': ['collections', 'read'],
  'configuracao.html': ['diagnostics', 'read'],
  'demo.html': ['diagnostics', 'read'],
  'diagnostico-catalogo.html': ['artworks', 'read'],
  'dominio-go-live.html': ['diagnostics', 'read'],
  'editor-registro.html': ['commercial', 'update'],
  'funil-comercial.html': ['commercial', 'read'],
  'go-live.html': ['diagnostics', 'read'],
  'historico-artista.html': ['artists', 'read'],
  'historico-obra.html': ['artworks', 'read'],
  'kanban-comercial.html': ['commercial', 'read'],
  'lancamento.html': ['diagnostics', 'read'],
  'lead-detalhe.html': ['leads', 'read'],
  'mvp-operacional.html': ['dashboard', 'read'],
  'obra-editor.html': ['artworks', 'update'],
  'onboarding-artista.html': ['artists', 'update'],
  'operacao-obras.html': ['artworks', 'read'],
  'operacao.html': ['dashboard', 'read'],
  'painel-admin.html': ['diagnostics', 'read'],
  'painel-artistas.html': ['artists', 'read'],
  'painel-briefings.html': ['briefs', 'read'],
  'painel-cadastros.html': ['artists', 'read'],
  'painel-certificados.html': ['certificates', 'read'],
  'painel-leads.html': ['leads', 'read'],
  'painel-mvp.html': ['dashboard', 'read'],
  'painel-obras.html': ['artworks', 'read'],
  'painel-pedidos.html': ['commercial', 'read'],
  'painel-piloto.html': ['pilot', 'read'],
  'painel-propostas.html': ['proposals', 'read'],
  'painel-qualidade.html': ['artworks', 'read'],
  'painel-reservas.html': ['reservations', 'read'],
  'painel-submissoes.html': ['submissions', 'read'],
  'painel-tarefas.html': ['tasks', 'read'],
  'painel.html': ['dashboard', 'read'],
  'piloto.html': ['pilot', 'read'],
  'propostas-admin.html': ['proposals', 'read'],
  'proposta-pdf.html': ['proposals', 'read'],
  'prospeccao-artistas.html': ['artists', 'read'],
  'revisao-catalogo.html': ['artworks', 'review'],
  'status.html': ['diagnostics', 'read'],
  'templates-comunicacao.html': ['commercial', 'read'],
  'upload-imagens.html': ['media', 'create']
});

export function permissionForInternalPage(page) {
  return PAGE_PERMISSIONS[page] || ['diagnostics', 'read'];
}
