#!/usr/bin/env bash
set -euo pipefail

base_url="${ARANDU_DATABASE_TEST_URL:-postgresql://postgres:postgres@localhost:5432/postgres}"
root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
clean_db="arandu_clean_test"
upgrade_db="arandu_upgrade_test"

psql "$base_url" -v ON_ERROR_STOP=1 -c "drop database if exists ${clean_db};"
psql "$base_url" -v ON_ERROR_STOP=1 -c "drop database if exists ${upgrade_db};"
psql "$base_url" -v ON_ERROR_STOP=1 -c "create database ${clean_db};"
psql "$base_url" -v ON_ERROR_STOP=1 -c "create database ${upgrade_db};"

database_url() {
  local name="$1"
  printf '%s/%s' "${base_url%/*}" "$name"
}

apply_file() {
  local database="$1"
  local file="$2"
  psql "$(database_url "$database")" -v ON_ERROR_STOP=1 -f "$root_dir/$file"
}

apply_file "$clean_db" "tests/database/bootstrap.sql"
while IFS= read -r file; do
  apply_file "$clean_db" "$file"
done < <(node -e "const m=require('./docs/supabase-migrations.json'); for (const f of m.cleanInstall) console.log(f)")
apply_file "$clean_db" "tests/database/transactions.sql"
apply_file "$clean_db" "tests/database/orders.sql"
apply_file "$clean_db" "tests/database/order-pr38-invariants.sql"
apply_file "$clean_db" "tests/database/email-outbox.sql"
apply_file "$clean_db" "tests/database/retention.sql"
apply_file "$clean_db" "tests/database/operational-status.sql"
apply_file "$clean_db" "tests/database/profile-access.sql"
apply_file "$clean_db" "tests/database/financial-procurement.sql"
apply_file "$clean_db" "tests/database/financial-procurement-hardening.sql"
apply_file "$clean_db" "tests/database/financial-pilot.sql"
apply_file "$clean_db" "tests/database/financial-enterprise-approvals.sql"
apply_file "$clean_db" "tests/database/financial-enterprise-drafts.sql"
apply_file "$clean_db" "tests/database/financial-collaboration.sql"
apply_file "$clean_db" "tests/database/financial-operational-search.sql"
apply_file "$clean_db" "tests/database/financial-renewals.sql"
apply_file "$clean_db" "tests/database/financial-rfq-editor.sql"
apply_file "$clean_db" "tests/database/financial-rfq-revisions.sql"
apply_file "$clean_db" "tests/database/financial-delivery.sql"
apply_file "$clean_db" "tests/database/financial-pilot-grade.sql"
apply_file "$clean_db" "tests/database/financial-pilot-operations.sql"
apply_file "$clean_db" "tests/database/financial-final-hardening.sql"
apply_file "$clean_db" "tests/database/financial-surface-hardening.sql"
apply_file "$clean_db" "tests/database/financial-approval-handoff.sql"
apply_file "$clean_db" "tests/database/financial-passport.sql"
# Reaplicação da migration financeira sobre a base já povoada: a rodada precisa
# ser idempotente antes de o rollback ser exercitado.
apply_file "$clean_db" "docs/supabase-financial-procurement.sql"
apply_file "$clean_db" "docs/supabase-financial-procurement-hardening.sql"
apply_file "$clean_db" "docs/supabase-financial-pilot.sql"
apply_file "$clean_db" "docs/supabase-financial-enterprise-approvals.sql"
apply_file "$clean_db" "docs/supabase-financial-enterprise-drafts.sql"
apply_file "$clean_db" "docs/supabase-financial-collaboration.sql"
apply_file "$clean_db" "docs/supabase-financial-operational-search.sql"
apply_file "$clean_db" "docs/supabase-financial-renewals.sql"
apply_file "$clean_db" "docs/supabase-financial-rfq-editor.sql"
apply_file "$clean_db" "docs/supabase-financial-rfq-revisions.sql"
apply_file "$clean_db" "docs/supabase-financial-delivery.sql"
apply_file "$clean_db" "docs/supabase-financial-pilot-grade.sql"
apply_file "$clean_db" "docs/supabase-financial-pilot-operations.sql"
apply_file "$clean_db" "docs/supabase-financial-final-hardening.sql"
apply_file "$clean_db" "docs/supabase-financial-pilot-surface-hardening.sql"
apply_file "$clean_db" "docs/supabase-financial-approval-handoff.sql"
apply_file "$clean_db" "docs/supabase-financial-passport.sql"
bash "$root_dir/tests/database/reservation-concurrency.sh" "$(database_url "$clean_db")"
bash "$root_dir/tests/database/order-concurrency.sh" "$(database_url "$clean_db")"

apply_file "$upgrade_db" "tests/database/bootstrap.sql"
while IFS= read -r file; do
  apply_file "$upgrade_db" "$file"
done < <(node -e "const m=require('./docs/supabase-migrations.json'); const i=m.cleanInstall.indexOf('docs/supabase-orders.sql'); for (const f of m.cleanInstall.slice(0,i)) console.log(f)")

apply_file "$upgrade_db" "docs/supabase-orders.sql"
apply_file "$upgrade_db" "docs/supabase-order-state-machine.sql"
apply_file "$upgrade_db" "docs/supabase-orders-hardening.sql"
apply_file "$upgrade_db" "docs/supabase-transactional-email-outbox.sql"
apply_file "$upgrade_db" "docs/supabase-retention-controls.sql"
apply_file "$upgrade_db" "docs/supabase-email-outbox-fencing.sql"

apply_file "$upgrade_db" "docs/supabase-orders-hardening.sql"
apply_file "$upgrade_db" "docs/supabase-transactional-email-outbox.sql"
apply_file "$upgrade_db" "docs/supabase-retention-controls.sql"
apply_file "$upgrade_db" "docs/supabase-email-outbox-fencing.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-email-outbox-fencing.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-retention-controls.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-transactional-email-outbox.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-orders-hardening.rollback.sql"

psql "$(database_url "$upgrade_db")" -v ON_ERROR_STOP=1 -c "do \$\$ begin if not has_function_privilege('service_role','public.transition_order_atomic(uuid,text,text,text,text,text,text,text)','EXECUTE') then raise exception 'rollback não restaurou state machine da PR #38'; end if; end \$\$;"

apply_file "$upgrade_db" "docs/supabase-orders-hardening.sql"
apply_file "$upgrade_db" "docs/supabase-transactional-email-outbox.sql"
apply_file "$upgrade_db" "docs/supabase-retention-controls.sql"
apply_file "$upgrade_db" "docs/supabase-email-outbox-fencing.sql"

apply_file "$upgrade_db" "tests/database/transactions.sql"
apply_file "$upgrade_db" "tests/database/orders.sql"
apply_file "$upgrade_db" "tests/database/order-pr38-invariants.sql"
apply_file "$upgrade_db" "tests/database/email-outbox.sql"
apply_file "$upgrade_db" "tests/database/retention.sql"
# Rollback do procurement financeiro e reaplicação, no banco de upgrade.
apply_file "$upgrade_db" "docs/supabase-financial-procurement.sql"
apply_file "$upgrade_db" "docs/supabase-financial-procurement-hardening.sql"
apply_file "$upgrade_db" "docs/supabase-financial-pilot.sql"
apply_file "$upgrade_db" "docs/supabase-financial-enterprise-approvals.sql"
apply_file "$upgrade_db" "docs/supabase-financial-enterprise-drafts.sql"
apply_file "$upgrade_db" "docs/supabase-financial-collaboration.sql"
apply_file "$upgrade_db" "docs/supabase-financial-operational-search.sql"
apply_file "$upgrade_db" "docs/supabase-financial-renewals.sql"
apply_file "$upgrade_db" "docs/supabase-financial-rfq-editor.sql"
apply_file "$upgrade_db" "docs/supabase-financial-rfq-revisions.sql"
apply_file "$upgrade_db" "docs/supabase-financial-delivery.sql"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-grade.sql"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-operations.sql"
apply_file "$upgrade_db" "docs/supabase-financial-final-hardening.sql"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-surface-hardening.sql"
apply_file "$upgrade_db" "ops/sql/pilot-isolation-canary.sql"
# A wrong marker cannot skip Passport checks or turn a partial schema green.
for marker in unknown financial-passport-1; do
  if rejection="$(psql "$(database_url "$upgrade_db")" -X -v ON_ERROR_STOP=1 -c "begin; update public.fin_settings set value='${marker}' where key='schema_version';" -f "$root_dir/ops/sql/pilot-isolation-canary.sql" 2>&1)"; then
    echo "Canary accepted an inconsistent schema marker" >&2; exit 1
  fi
  if [ "$marker" = unknown ]; then expected='CANÁRIO: schema não suportado'; else expected='CANÁRIO: schema_version e tabelas Passport divergentes'; fi
  [[ "$rejection" == *"$expected"* ]] || { echo "Canary failed for an unexpected reason" >&2; exit 1; }
done
apply_file "$upgrade_db" "docs/supabase-financial-approval-handoff.sql"
apply_file "$upgrade_db" "docs/supabase-financial-passport.sql"
apply_file "$upgrade_db" "ops/sql/pilot-isolation-canary.sql"
apply_file "$upgrade_db" "tests/database/financial-passport.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-passport.rollback.sql"
psql "$(database_url "$upgrade_db")" -v ON_ERROR_STOP=1 -c "do \$\$ begin if to_regclass('public.fin_rfq_profile_snapshots') is not null or to_regclass('public.fin_company_profile_history') is not null or exists(select 1 from information_schema.columns where table_name='fin_company_profiles' and column_name='verified_at') or not has_table_privilege('authenticated','public.fin_company_profiles','INSERT') or (select value from public.fin_settings where key='schema_version') <> 'financial-approval-handoff-1' then raise exception 'rollback do Financial Passport incompleto'; end if; end \$\$;"
apply_file "$upgrade_db" "docs/supabase-financial-passport.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-passport.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-approval-handoff.rollback.sql"
psql "$(database_url "$upgrade_db")" -v ON_ERROR_STOP=1 -c "do \$\$ begin if (select prosrc from pg_proc where oid = to_regprocedure('public.fin_notify_event()')) like '%v_next%' or (select value from public.fin_settings where key='schema_version') <> 'financial-surface-hardening-1' or has_function_privilege('authenticated','public.fin_notify_event()','EXECUTE') then raise exception 'rollback do aviso ao próximo aprovador incompleto'; end if; end \$\$;"
apply_file "$upgrade_db" "docs/supabase-financial-approval-handoff.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-approval-handoff.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-pilot-surface-hardening.rollback.sql"
psql "$(database_url "$upgrade_db")" -v ON_ERROR_STOP=1 -c "do \$\$ begin if not has_function_privilege('authenticated','public.fin_pilot_access_allowed(text)','EXECUTE') or (select relrowsecurity from pg_class where oid='public.artwork_events'::regclass) or (select value from public.fin_settings where key='schema_version') <> 'financial-final-hardening-1' then raise exception 'rollback do hardening da superfície incompleto'; end if; end \$\$;"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-surface-hardening.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-pilot-surface-hardening.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-final-hardening.rollback.sql"
psql "$(database_url "$upgrade_db")" -v ON_ERROR_STOP=1 -c "do \$\$ begin if to_regclass('public.fin_invite_acceptance_denials') is not null or to_regprocedure('public.fin_platform_role()') is not null or exists(select 1 from information_schema.columns where table_name='fin_rfq_invites' and column_name='recipient_mode') then raise exception 'rollback do hardening final incompleto'; end if; end \$\$;"
apply_file "$upgrade_db" "docs/supabase-financial-final-hardening.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-final-hardening.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-pilot-operations.rollback.sql"
psql "$(database_url "$upgrade_db")" -v ON_ERROR_STOP=1 -c "do \$\$ begin if (select prosrc from pg_proc where oid = to_regprocedure('public.fin_accept_provider_invite(text,uuid)')) like '%i.provider_organization_id = p_provider_org%' then raise exception 'rollback do vínculo do convite incompleto'; end if; end \$\$;"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-operations.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-pilot-operations.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-pilot-grade.rollback.sql"
psql "$(database_url "$upgrade_db")" -v ON_ERROR_STOP=1 -c "do \$\$ begin if to_regclass('public.fin_private_documents') is not null or to_regprocedure('public.fin_ops_overview()') is not null or exists(select 1 from information_schema.columns where table_name='fin_members' and column_name='display_name') then raise exception 'rollback da rodada de piloto incompleto'; end if; end \$\$;"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-grade.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-pilot-grade.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-delivery.rollback.sql"
psql "$(database_url "$upgrade_db")" -v ON_ERROR_STOP=1 -c "do \$\$ begin if exists(select 1 from information_schema.columns where table_name='fin_comments' and column_name='parent_id') or to_regprocedure('public.fin_run_renewal_schedule(date)') is not null then raise exception 'rollback da entrega operacional incompleto'; end if; end \$\$;"
apply_file "$upgrade_db" "docs/supabase-financial-delivery.sql"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-grade.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-pilot-grade.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-delivery.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-rfq-revisions.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-rfq-editor.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-renewals.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-operational-search.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-collaboration.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-enterprise-drafts.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-enterprise-approvals.rollback.sql"
apply_file "$upgrade_db" "docs/rollback/supabase-financial-procurement.rollback.sql"
psql "$(database_url "$upgrade_db")" -v ON_ERROR_STOP=1 -c "do \$\$ begin if to_regclass('public.fin_rfqs') is not null then raise exception 'rollback financeiro não removeu as tabelas'; end if; end \$\$;"
apply_file "$upgrade_db" "docs/supabase-financial-procurement.sql"
apply_file "$upgrade_db" "docs/supabase-financial-procurement-hardening.sql"
apply_file "$upgrade_db" "docs/supabase-financial-pilot.sql"
apply_file "$upgrade_db" "docs/supabase-financial-enterprise-approvals.sql"
apply_file "$upgrade_db" "docs/supabase-financial-enterprise-drafts.sql"
apply_file "$upgrade_db" "docs/supabase-financial-collaboration.sql"
apply_file "$upgrade_db" "docs/supabase-financial-operational-search.sql"
apply_file "$upgrade_db" "docs/supabase-financial-renewals.sql"
apply_file "$upgrade_db" "docs/supabase-financial-rfq-editor.sql"
apply_file "$upgrade_db" "docs/supabase-financial-rfq-revisions.sql"
apply_file "$upgrade_db" "docs/supabase-financial-delivery.sql"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-grade.sql"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-operations.sql"
apply_file "$upgrade_db" "docs/supabase-financial-final-hardening.sql"
apply_file "$upgrade_db" "docs/supabase-financial-pilot-surface-hardening.sql"
apply_file "$upgrade_db" "docs/supabase-financial-approval-handoff.sql"
apply_file "$upgrade_db" "docs/supabase-financial-passport.sql"
apply_file "$upgrade_db" "tests/database/financial-procurement.sql"
apply_file "$upgrade_db" "tests/database/financial-procurement-hardening.sql"
apply_file "$upgrade_db" "tests/database/financial-pilot.sql"
apply_file "$upgrade_db" "tests/database/financial-enterprise-approvals.sql"
apply_file "$upgrade_db" "tests/database/financial-enterprise-drafts.sql"
apply_file "$upgrade_db" "tests/database/financial-collaboration.sql"
apply_file "$upgrade_db" "tests/database/financial-operational-search.sql"
apply_file "$upgrade_db" "tests/database/financial-renewals.sql"
apply_file "$upgrade_db" "tests/database/financial-rfq-editor.sql"
apply_file "$upgrade_db" "tests/database/financial-rfq-revisions.sql"
apply_file "$upgrade_db" "tests/database/financial-delivery.sql"
apply_file "$upgrade_db" "tests/database/financial-pilot-grade.sql"
apply_file "$upgrade_db" "tests/database/financial-pilot-operations.sql"
apply_file "$upgrade_db" "tests/database/financial-final-hardening.sql"
apply_file "$upgrade_db" "tests/database/financial-surface-hardening.sql"
apply_file "$upgrade_db" "tests/database/financial-approval-handoff.sql"
apply_file "$upgrade_db" "tests/database/financial-passport.sql"
bash "$root_dir/tests/database/email-outbox-concurrency.sh" "$(database_url "$upgrade_db")"

echo "Arandu Database Integration Tests"
echo "Instalação limpa, upgrade, reaplicação, rollback, RLS, transações, pedidos, invariantes PR38, outbox, fencing de workers, retenção, procurement financeiro e operação real do piloto (convite, janela de envio, aviso de renovação), finance_ops, destinatário do convite superfície exposta ao PostgREST (fidelidade aos default privileges do Supabase, matriz adversarial entre tenants) aviso ao próximo aprovador da cadeia e Financial Passport (proveniência, histórico, snapshot imutável na RFQ, negação a provedor e a outro tenant) aprovados."
